"""
smoke_test.jl
=============
Cheap, fast pre-flight check — run it BEFORE submitting a multi-hour calibration
so a broken build / bad edit / missing input is caught in seconds, not on day 2.

It verifies, in order:
  1. core Julia packages load,
  2. every SMM source file PARSES and includes without error
     (this is what catches a syntax mistake in an edit to smm_estimation.jl etc.),
  3. the setup contract holds (params/moments/bounds dimensions in sync),
  4. the required raw input files are present.

Exits 0 on success, 1 on any failure, so the SLURM script can abort the run:

    julia --project=. smoke_test.jl
"""

using Printf

# Smoke mode: lets smm_estimation.jl include with placeholder data moments on a
# fresh bundle (CSVs are built later in the pipeline). Real estimation runs do
# NOT set this and hard-error on missing/stale moment files (2026-07-08).
ENV["SMM_SMOKE"] = "1"

const JD   = @__DIR__
const REPO = abspath(joinpath(JD, "..", ".."))
const DATA = joinpath(REPO, "Data")

const FAILS = String[]
function check(name::AbstractString, ok::Bool, msg::AbstractString="")
    if ok
        @printf "  OK    %s\n" name
    else
        push!(FAILS, name)
        @printf "  FAIL  %s  %s\n" name msg
    end
    return ok
end

println("="^60); println("  NK-IOSOE smoke test"); println("="^60)
@printf "Julia %s | %d thread(s) | dir %s\n\n" string(VERSION) Threads.nthreads() JD

# --- 1. packages ----------------------------------------------------------- #
println("--- packages ---")
for p in ["LinearAlgebra","Statistics","StatsBase","Printf","Random","NLsolve",
          "CSV","DataFrames","SparseArrays","CMAEvolutionStrategy","Dynare"]
    try
        @eval using $(Symbol(p))
        check(p, true)
    catch e
        check(p, false, sprint(showerror, e))
    end
end

# --- 2. source files parse + include (syntax check) ------------------------ #
# smm_model_moments.jl already includes the steady-state + utils files; including
# smm_estimation.jl runs its top-level data-moment load, which safely falls back
# to placeholders when the moment CSVs do not exist yet (pre-compile stage).
println("\n--- source includes (syntax check) ---")
cd(JD) do
    for s in ["steady_ntwsoe_system.jl","steady_ntwsoe.jl","utils.jl",
              "smm_model_moments.jl","smm_estimation.jl"]
        try
            Base.include(Main, joinpath(JD, s))
            check(s, true)
        catch e
            check(s, false, sprint(showerror, e))
        end
    end
end

# --- 3. setup contract ----------------------------------------------------- #
println("\n--- setup contract ---")
try
    Base.invokelatest(getfield(Main, :validate_smm_setup), getfield(Main, :data_moments))
    check("validate_smm_setup", true)
catch e
    check("validate_smm_setup", false, sprint(showerror, e))
end

# --- 4. required input files ----------------------------------------------- #
println("\n--- input files ---")
for f in ["sector_calibration.csv", "IO_2021_chile.csv"]
    check("Data/$f", isfile(joinpath(DATA, f)))
end
# The DOMESTIC matrix is what the model actually wants (2026-08-19); the total
# matrix above is only the fallback. Generated by build_sector_calibration.py.
check("Data/IO_2021_chile_domestic.csv", isfile(joinpath(DATA, "IO_2021_chile_domestic.csv")))

# --- 5. capital block (LPR semi-fixed capital, 2026-08-20) ----------------- #
# The dimension checks above cannot see these: alpha_K / chi_I / nu are read at
# runtime from CSVs and from params_jl.mod, so a stale file gives NaNs rather
# than an error. Checked explicitly here and in validate_smm_setup.
println("\n--- capital block ---")
check("Data/capital_calibration.csv", isfile(joinpath(DATA, "capital_calibration.csv")))
try
    d = Base.invokelatest(getfield(Main, :CSV).read,
                          joinpath(DATA, "sector_calibration.csv"),
                          getfield(Main, :DataFrames).DataFrame)
    has = hasproperty(d, :alpha_K) && hasproperty(d, :chi_I)
    check("sector_calibration.csv has alpha_K + chi_I", has,
          has ? "" : "run python3 Data/build_sector_calibration.py")
    if has
        check("chi_I sums to 1", abs(sum(d.chi_I) - 1) < 1e-8, "= $(sum(d.chi_I))")
        lab = 1 .- d.alpha .- d.alpha_V .- d.alpha_K
        check("labour weight > 0 in all sectors", all(>(0), lab),
              "violations in $(findall(<=(0), lab))")
        @printf "        mean alpha_K = %.3f, mean labour weight = %.3f\n" (
            sum(d.alpha_K)/length(d.alpha_K)) (sum(lab)/length(lab))
    end
catch e
    check("sector_calibration.csv readable", false, sprint(showerror, e))
end
# params_jl.mod must postdate the capital block, or pvec() returns NaN for every
# capital parameter and the estimation silently solves a meaningless model.
let pf = joinpath(JD, "mod", "params_jl.mod")
    if isfile(pf)
        txt = read(pf, String)
        missing_p = filter(nm -> !occursin(Regex("(^|\\n)\\s*$(nm)\\s*="), txt),
                           ["alphaK_1","Kbar_1","chiI_1","RKss_1","nuK","PIinv_ss"])
        check("params_jl.mod has the capital parameters", isempty(missing_p),
              isempty(missing_p) ? "" :
              "missing $(join(missing_p, ", ")) — re-run main_SOE_gap.jl")
    else
        check("mod/params_jl.mod", false, "run main_SOE_gap.jl first")
    end
end

println("\n" * "="^60)
if isempty(FAILS)
    println("  SMOKE TEST PASSED"); exit(0)
else
    @printf "  SMOKE TEST FAILED (%d): %s\n" length(FAILS) join(FAILS, ", ")
    exit(1)
end
