"""
utils.jl
========
Helper functions for the NK-IOSOE Julia/Dynare.jl pipeline.

Contents:
  - write_params_mod   : generate params_jl.mod (read by NK_SOE_lev_gap2.mod)
  - safe_spearman      : Spearman corr that returns 0 when model vec is uniform
  - local_dlyap        : discrete Lyapunov solver (doubling algorithm)
  - ternary_str        : conditional string helper
"""

using LinearAlgebra, StatsBase, Printf

# =========================================================================== #
#  params_jl.mod generator                                                     #
#                                                                              #
#  NK_SOE_lev_gap2.mod does  @#include "params_jl.mod"  instead of the        #
#  old  load params_val_ul.mat.  This function writes that file with every     #
#  parameter value pre-expanded, so Dynare.jl never needs MATLAB or Octave.   #
# =========================================================================== #

"""
    write_params_mod(mod_dir, p) -> String

Generate `mod_dir/params_jl.mod` containing explicit Dynare parameter
assignments for all scalars, sectoral vectors and the IO matrix.

Arguments:
  mod_dir  : directory that contains NK_SOE_lev_gap2.mod
  p        : NamedTuple or Dict with all computed steady-state values

The returned string is the path to the written file.
"""
function write_params_mod(mod_dir::String, p::NamedTuple)
    path = joinpath(mod_dir, "params_jl.mod")
    nsec = p.nsec

    open(path, "w") do io
        println(io, "// -------------------------------------------------------")
        println(io, "// params_jl.mod  —  auto-generated by main_SOE_gap.jl")
        println(io, "// Do NOT edit manually; re-run main_SOE_gap.jl to refresh.")
        println(io, "// -------------------------------------------------------")
        println(io)

        # ---- Scalar structural parameters -------------------------------- #
        _wp(io, "sigma_i",      p.sigma_i_val)
        _wp(io, "sigma_L_agg",  p.sigma_L_agg_val)
        _wp(io, "sigma_om",     p.sigma_om_val)
        _wp(io, "ilabcosts",    p.ilabcosts_val)
        _wp(io, "gamma",        p.gamma_val)
        _wp(io, "psi",          1.0)
        _wp(io, "beta",         p.beta_val)
        _wp(io, "phi",          p.phi_val)
        _wp(io, "epsilon",      10.0)
        _wp(io, "rho",          p.rho_val)
        _wp(io, "rho_om1",      p.rho_om1_val)
        _wp(io, "rho_om2",      p.rho_om2_val)
        _wp(io, "rho_tfp1",     p.rho_tfp1_val)
        _wp(io, "rho_tfp2",     p.rho_tfp2_val)
        _wp(io, "rhoi",         0.5)          # rhoi = 0.5 + 0*rhoi_val
        _wp(io, "rhoirule",     p.rhoirule_val)
        _wp(io, "ombar",        p.ombar_val)
        _wp(io, "chii_b",       p.chii_b_val)
        _wp(io, "bbar",         p.bbar_val)
        _wp(io, "epsilonX",     p.epsilonX_val)
        _wp(io, "omegaX",       p.omegaX_val)
        _wp(io, "ystar_ss",     p.ystar_ss_val)
        _wp(io, "etastar",      p.etastar_val)
        _wp(io, "epsilonV",     p.epsilonV_val)
        _wp(io, "kappaV",       p.kappaV_val)
        _wp(io, "sigmaH",       p.sigmaH_val)
        _wp(io, "Pistar_ss",    p.Pistar_ss_val)
        _wp(io, "PVstar_ss",    p.PVstar_ss_val)
        _wp(io, "rho_pvstar",   p.rho_pvstar_val)
        _wp(io, "sigma_pvstar", p.sigma_pvstar_val)
        _wp(io, "rho_xi",       p.rho_xi_val)
        _wp(io, "sigma_xi",     p.sigma_xi_val)
        _wp(io, "Rworld_ss",    p.Rworld_ss_val)
        println(io)

        # ---- Steady-state scalars ---------------------------------------- #
        # pi_ss = 1 (zero net domestic inflation in SS)
        # r_ss = Pistar_ss / beta (from household Euler equation)
        _wp(io, "pi_ss",   1.0)
        _wp(io, "r_ss",    p.Pistar_ss_val / p.beta_val)
        _wp(io, "w_ss",    p.w_ss)
        _wp(io, "C_ss",    p.C_ss)
        _wp(io, "GDP_ss",  p.GDP_ss)
        _wp(io, "N_ss",    p.N_ss)
        _wp(io, "p_s_ss",  p.p_s_ss)
        _wp(io, "p_g_ss",  p.p_g_ss)
        _wp(io, "C_s_ss",  p.C_s_ss)
        _wp(io, "C_g_ss",  p.C_g_ss)
        _wp(io, "Bstar_ss",     p.Bstar_ss)
        _wp(io, "Q_ss",         p.Q_ss)
        _wp(io, "TB_ss",        p.TB_ss)
        _wp(io, "PX_ss",        p.PX_ss)
        _wp(io, "V_ss",         p.V_ss)
        _wp(io, "CF_ss",        p.CF_ss)
        _wp(io, "CFg_total_ss", p.CFg_total_ss)
        _wp(io, "CFs_total_ss", p.CFs_total_ss)
        _wp(io, "IMP_ss",     p.IMP_ss_val)
        _wp(io, "Ctot_ss",    p.Ctot_ss_val)
        _wp(io, "Ctotg_ss",   p.Ctotg_ss_val)
        _wp(io, "Ctots_ss",   p.Ctots_ss_val)
        _wp(io, "VA_ss",      p.VA_ss_val)
        _wp(io, "M_tot_ss",   p.M_tot_ss)
        _wp(io, "Y_ss",       p.Y_tot_ss)       # Y_ss ≡ Y_tot_ss
        println(io)

        # ---- Shock activation flags ------------------------------------- #
        println(io, "// Shock variances (0 = off, 1 = on; amplitude inside model equations)")
        _wp(io, "shock_eps_om",     p.shock_eps_om_val)
        _wp(io, "shock_eps_i",      p.shock_eps_i_val)
        _wp(io, "shock_eps_pvstar", p.shock_eps_pvstar_val)
        _wp(io, "shock_eps_xi",     p.shock_eps_xi_val)
        println(io)

        # ---- Sectoral parameters (i = 1..nsec) -------------------------- #
        println(io, "// Sectoral parameters")
        for i in 1:nsec
            _wp(io, "gammag_$(i)",       p.modgammag[i])
            _wp(io, "gammas_$(i)",       p.modgammas[i])
            _wp(io, "alpha_$(i)",        p.modalpha[i])
            _wp(io, "epsY_$(i)",         p.modepsY[i])
            _wp(io, "epsM_$(i)",         p.modepsM[i])
            _wp(io, "kappa_$(i)",        p.modkappa[i])
            _wp(io, "dummyg_$(i)",       Float64(p.goods[i]))
            _wp(io, "dummys_$(i)",       Float64(p.services[i]))
            _wp(io, "cl_$(i)",           p.modcl[i])
            _wp(io, "clneg_$(i)",        p.modclneg[i])
            _wp(io, "cm_$(i)",           p.modcm[i])
            _wp(io, "chiX_$(i)",         p.modchiX[i])
            _wp(io, "alphaV_$(i)",       p.modalphaV[i])
            _wp(io, "varrho_$(i)",       p.modvarrho[i])
            _wp(io, "isigma_tfp_$(i)",   p.isigma_tfp_val[i])
            _wp(io, "shock_epsA_$(i)",   p.shock_epsA_val[i])
            # Sectoral steady-state scalars (indexed, referenced in initval block)
            _wp(io, "PL_ss$(i)",  p.PL_ss[i])
            _wp(io, "CFg_ss$(i)", p.CFg_ss[i])
            _wp(io, "CFs_ss$(i)", p.CFs_ss[i])
            _wp(io, "CHg_ss$(i)", p.CHg_ss[i])
            _wp(io, "CHs_ss$(i)", p.CHs_ss[i])
            _wp(io, "Vi_ss$(i)",  p.Vi_ss[i])
            _wp(io, "PH_ss$(i)",  p.pH_ss[i])
            _wp(io, "MC_ss$(i)",  p.MCi_ss[i])
            _wp(io, "Y_ss$(i)",   p.Yi_ss[i])
            _wp(io, "L_ss$(i)",   p.L_ss[i])
            _wp(io, "Cgi_ss$(i)", p.C_gi_ss[i])
            _wp(io, "Csi_ss$(i)", p.C_si_ss[i])
            _wp(io, "P_ss$(i)",   p.P_ss[i])
            _wp(io, "PMi_ss$(i)", p.PMi_ss[i])
            _wp(io, "Mi_ss$(i)",  p.M_ss[i])
            println(io)
        end

        # ---- IO matrix (beta_i_j for i,j = 1..nsec) --------------------- #
        println(io, "// IO matrix: beta_i_j = share of inputs sector i sources from sector j")
        for i in 1:nsec, j in 1:nsec
            _wp(io, "beta_$(i)_$(j)", p.modbeta[i, j])
        end
    end

    return path
end

# Internal helper: write one Dynare parameter assignment
function _wp(io::IO, name::String, val::Real)
    # Use full precision; avoid scientific notation for very small/large values
    @printf io "%s = %.15g;\n" name val
end


# =========================================================================== #
#  Rank correlation                                                            #
# =========================================================================== #

"""
    safe_spearman(x, y) -> Float64

Spearman rank correlation. Returns 0.0 when `x` is nearly uniform (model std
devs identical across sectors), matching the smm_model_moments.m behaviour.
"""
function safe_spearman(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    std(x) < 1e-12 * (abs(mean(x)) + 1e-12) && return 0.0
    return corspearman(x, y)
end


# =========================================================================== #
#  Discrete Lyapunov equation                                                  #
# =========================================================================== #

"""
    local_dlyap(A, Q) -> P

Solve  P = A P Aᵀ + Q  by the matrix-doubling algorithm.
Equivalent to MATLAB's dlyap(A', Q).
"""
function local_dlyap(A::AbstractMatrix{<:Real}, Q::AbstractMatrix{<:Real};
                     maxiter::Int=500, tol::Real=1e-14)
    P  = copy(Q)
    Ai = copy(A)
    for _ in 1:maxiter
        P_new = Ai * P * Ai' + P
        err   = norm(P_new - P, Inf) / (norm(P, Inf) + 1e-14)
        P     = (P_new + P_new') / 2
        Ai    = Ai * Ai
        err < tol && break
    end
    return (P + P') / 2
end


# =========================================================================== #
#  Misc                                                                        #
# =========================================================================== #

ternary_str(cond::Bool, s_true::String, s_false::String) = cond ? s_true : s_false
