"""
utils.jl
========
Helper functions for the NK-IOSOE Julia/Dynare.jl pipeline.

Contents:
  - write_params_mod   : generate params_jl.mod (read by NK_SOE_lev_gap2.mod)
  - safe_spearman      : Spearman corr that returns 0 when model vec is uniform
  - local_dlyap        : discrete Lyapunov solver (doubling algorithm)
  - ternary_str        : conditional string helper
"""

using LinearAlgebra, StatsBase, Printf

# =========================================================================== #
#  params_jl.mod generator                                                     #
#                                                                              #
#  NK_SOE_lev_gap2.mod does  @#include "params_jl.mod"  instead of the        #
#  old  load params_val_ul.mat.  This function writes that file with every     #
#  parameter value pre-expanded, so Dynare.jl never needs MATLAB or Octave.   #
# =========================================================================== #

"""
    write_params_mod(mod_dir, p) -> String

Generate `mod_dir/params_jl.mod` containing explicit Dynare parameter
assignments for all scalars, sectoral vectors and the IO matrix.

Arguments:
  mod_dir  : directory that contains NK_SOE_lev_gap2.mod
  p        : NamedTuple or Dict with all computed steady-state values

The returned string is the path to the written file.
"""
function write_params_mod(mod_dir::String, p::NamedTuple)
    path = joinpath(mod_dir, "params_jl.mod")
    nsec = p.nsec

    open(path, "w") do io
        println(io, "// -------------------------------------------------------")
        println(io, "// params_jl.mod  —  auto-generated by main_SOE_gap.jl")
        println(io, "// Do NOT edit manually; re-run main_SOE_gap.jl to refresh.")
        println(io, "// -------------------------------------------------------")
        println(io)

        # ---- Scalar structural parameters -------------------------------- #
        _wp(io, "sigma_i",      p.sigma_i_val)
        _wp(io, "sigma_L_agg",  p.sigma_L_agg_val)
        _wp(io, "ilabcosts",    p.ilabcosts_val)
        _wp(io, "gamma",        p.gamma_val)
        _wp(io, "psi",          1.0)
        # GHH disutility scale chi0 = chi_weight * C_ss^gamma (holds SS at KPR
        # values). Falls back to C_ss^gamma (chi_weight = 1) if not supplied.
        _wp(io, "chi0",         get(p, :chi0_val, p.C_ss^p.gamma_val))
        _wp(io, "beta",         p.beta_val)
        _wp(io, "phi",          p.phi_val)
        _wp(io, "epsilon",      10.0)
        _wp(io, "rho",          p.rho_val)
        _wp(io, "rho_om1",      p.rho_om1_val)
        # rho_tfp1 accepts a scalar (common TFP persistence) or an nsec-vector
        # (sector-specific, e.g. transitory agriculture shock with half-life of
        # half a quarter → ρ = 0.25).  The lev mod uses the sectoral parameters
        # rho_tfp1_<i> (written in the loop below); the scalar alias is kept for
        # the SMM mod, whose equations use the common rho_tfp1.  When a vector
        # is passed, the alias takes the LAST entry (an unshocked sector =
        # common persistence) — it is unused by the lev mod in that case.
        _rho_tfp1_vec = p.rho_tfp1_val isa AbstractVector ?
            collect(Float64, p.rho_tfp1_val) : fill(Float64(p.rho_tfp1_val), p.nsec)
        _wp(io, "rho_tfp1",     _rho_tfp1_vec[end])
        _wp(io, "rho_tfp2",     p.rho_tfp2_val)
        _wp(io, "rhoi",         0.5)          # rhoi = 0.5 + 0*rhoi_val
        _wp(io, "rhoirule",     p.rhoirule_val)
        _wp(io, "ombar",        p.ombar_val)
        _wp(io, "chii_b",       p.chii_b_val)
        _wp(io, "bbar",         p.bbar_val)
        _wp(io, "epsilonX",     p.epsilonX_val)
        _wp(io, "omegaX",       p.omegaX_val)
        _wp(io, "ystar_ss",     p.ystar_ss_val)
        _wp(io, "etastar",      p.etastar_val)
        _wp(io, "epsilonV",     p.epsilonV_val)
        _wp(io, "kappaV",       p.kappaV_val)
        _wp(io, "sigmaH",       p.sigmaH_val)
        _wp(io, "Pistar_ss",    p.Pistar_ss_val)
        _wp(io, "PVstar_ss",    p.PVstar_ss_val)
        _wp(io, "rho_pvstar",   p.rho_pvstar_val)
        _wp(io, "sigma_pvstar", p.sigma_pvstar_val)
        _wp(io, "rho_xi",       p.rho_xi_val)
        _wp(io, "sigma_xi",     p.sigma_xi_val)
        _wp(io, "Rworld_ss",    p.Rworld_ss_val)
        # Sticky wages (Rotemberg wage PC). Defaults apply unless the driver
        # passes epsw_val / kappaw_val in the params NamedTuple.
        # kappaw default 115 ≈ Calvo wage duration of 4 quarters:
        # slope = (1-θw)(1-βθw)/θw = 0.0868 with θw=0.75, β=0.986 → κw = εw/slope.
        # kappaw = 0 → flexible wages (nests the pre-2026-07 model exactly).
        _wp(io, "epsw",   get(p, :epsw_val,   10.0))
        _wp(io, "kappaw", get(p, :kappaw_val, 115.0))
        # Oil sector scalar parameters
        _wp(io, "epsilonV_oil",    p.epsilonV_oil_val)
        _wp(io, "rho_postar",      p.rho_postar_val)
        _wp(io, "sigma_postar",    p.sigma_postar_val)
        _wp(io, "POstar_ss",       p.POstar_ss_val)
        _wp(io, "shock_eps_postar",p.shock_eps_postar_val)
        println(io)

        # ---- Steady-state scalars ---------------------------------------- #
        # pi_ss = 1 (zero net domestic inflation in SS)
        # r_ss = Pistar_ss / beta (from household Euler equation)
        _wp(io, "pi_ss",   1.0)
        _wp(io, "r_ss",    p.Pistar_ss_val / p.beta_val)
        _wp(io, "w_ss",    p.w_ss)
        _wp(io, "C_ss",    p.C_ss)
        _wp(io, "GDP_ss",  p.GDP_ss)
        _wp(io, "N_ss",    p.N_ss)
        _wp(io, "p_s_ss",  p.p_s_ss)
        _wp(io, "p_g_ss",  p.p_g_ss)
        _wp(io, "C_s_ss",  p.C_s_ss)
        _wp(io, "C_g_ss",  p.C_g_ss)
        _wp(io, "Bstar_ss",     p.Bstar_ss)
        _wp(io, "Q_ss",         p.Q_ss)
        _wp(io, "TB_ss",        p.TB_ss)
        _wp(io, "PX_ss",        p.PX_ss)
        _wp(io, "V_ss",         p.V_ss)
        _wp(io, "CF_ss",        p.CF_ss)
        _wp(io, "CFg_total_ss", p.CFg_total_ss)
        _wp(io, "CFs_total_ss", p.CFs_total_ss)
        _wp(io, "IMP_ss",     p.IMP_ss_val)
        _wp(io, "Ctot_ss",    p.Ctot_ss_val)
        _wp(io, "Ctotg_ss",   p.Ctotg_ss_val)
        _wp(io, "Ctots_ss",   p.Ctots_ss_val)
        _wp(io, "VA_ss",      p.VA_ss_val)
        _wp(io, "M_tot_ss",   p.M_tot_ss)
        _wp(io, "Y_ss",       p.Y_tot_ss)       # Y_ss ≡ Y_tot_ss
        println(io)

        # ---- Shock activation flags ------------------------------------- #
        println(io, "// Shock variances (0 = off, 1 = on; amplitude inside model equations)")
        _wp(io, "shock_eps_i",      p.shock_eps_i_val)
        _wp(io, "shock_eps_pvstar", p.shock_eps_pvstar_val)
        _wp(io, "shock_eps_xi",     p.shock_eps_xi_val)
        # NOTE: the aggregate eps_om shock was removed in the unified model; demand
        # is now sectoral (eps_om_1..nsec). The per-sector activation flags
        # shock_eps_om_i and std devs sigma_om_i are written below. Do NOT write a
        # scalar shock_eps_om / sigma_om / rho_om2 — those parameters no longer
        # exist in NK_SOE_lev_gap2.mod and Dynare would reject them.
        println(io)

        # ---- Option-A: 12 sectoral demand shock parameters -------------- #
        println(io, "// Option-A: sectoral demand shock std devs and activation flags")
        for i in 1:nsec
            _wp(io, "sigma_om_$(i)",     p.sigma_om_vec[i])
        end
        for i in 1:nsec
            _wp(io, "shock_eps_om_$(i)", p.shock_eps_om_vec[i])
        end
        println(io)

        # ---- Sectoral parameters (i = 1..nsec) -------------------------- #
        println(io, "// Sectoral parameters")
        for i in 1:nsec
            _wp(io, "gammag_$(i)",       p.modgammag[i])
            _wp(io, "gammas_$(i)",       p.modgammas[i])
            _wp(io, "alpha_$(i)",        p.modalpha[i])
            _wp(io, "epsY_$(i)",         p.modepsY[i])
            _wp(io, "epsM_$(i)",         p.modepsM[i])
            _wp(io, "kappa_$(i)",        p.modkappa[i])
            _wp(io, "dummyg_$(i)",       Float64(p.goods[i]))
            _wp(io, "dummys_$(i)",       Float64(p.services[i]))
            _wp(io, "cl_$(i)",           p.modcl[i])
            _wp(io, "clneg_$(i)",        p.modclneg[i])
            _wp(io, "cm_$(i)",           p.modcm[i])
            _wp(io, "chiX_$(i)",         p.modchiX[i])
            _wp(io, "alphaV_$(i)",       p.modalphaV[i])
            _wp(io, "varrho_$(i)",       p.modvarrho[i])
            _wp(io, "isigma_tfp_$(i)",   p.isigma_tfp_val[i])
            _wp(io, "rho_tfp1_$(i)",     _rho_tfp1_vec[i])
            _wp(io, "shock_epsA_$(i)",   p.shock_epsA_val[i])
            _wp(io, "alphaOilShare_$(i)", p.modalphaOil[i])
            _wp(io, "PIV_ss$(i)",         p.PIV_ss_vec[i])
            # Sectoral steady-state scalars (indexed, referenced in initval block)
            _wp(io, "PL_ss$(i)",  p.PL_ss[i])
            _wp(io, "CFg_ss$(i)", p.CFg_ss[i])
            _wp(io, "CFs_ss$(i)", p.CFs_ss[i])
            _wp(io, "CHg_ss$(i)", p.CHg_ss[i])
            _wp(io, "CHs_ss$(i)", p.CHs_ss[i])
            _wp(io, "Vi_ss$(i)",  p.Vi_ss[i])
            _wp(io, "PH_ss$(i)",  p.pH_ss[i])
            _wp(io, "MC_ss$(i)",  p.MCi_ss[i])
            _wp(io, "Y_ss$(i)",   p.Yi_ss[i])
            _wp(io, "L_ss$(i)",   p.L_ss[i])
            _wp(io, "Cgi_ss$(i)", p.C_gi_ss[i])
            _wp(io, "Csi_ss$(i)", p.C_si_ss[i])
            _wp(io, "P_ss$(i)",   p.P_ss[i])
            _wp(io, "PMi_ss$(i)", p.PMi_ss[i])
            _wp(io, "Mi_ss$(i)",  p.M_ss[i])
            println(io)
        end

        # ---- IO matrix (beta_i_j for i,j = 1..nsec) --------------------- #
        println(io, "// IO matrix: beta_i_j = share of inputs sector i sources from sector j")
        for i in 1:nsec, j in 1:nsec
            _wp(io, "beta_$(i)_$(j)", p.modbeta[i, j])
        end
    end

    return path
end

# Internal helper: write one Dynare parameter assignment
function _wp(io::IO, name::String, val::Real)
    # Use full precision; avoid scientific notation for very small/large values
    @printf io "%s = %.15g;\n" name val
end


# =========================================================================== #
#  Rank correlation                                                            #
# =========================================================================== #

"""
    safe_spearman(x, y) -> Float64

Spearman rank correlation. Returns 0.0 when `x` is nearly uniform (model std
devs identical across sectors), matching the smm_model_moments.m behaviour.
"""
function safe_spearman(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    std(x) < 1e-12 * (abs(mean(x)) + 1e-12) && return 0.0
    return corspearman(x, y)
end


# =========================================================================== #
#  Discrete Lyapunov equation                                                  #
# =========================================================================== #

"""
    local_dlyap(A, Q) -> P

Solve  P = A P Aᵀ + Q  by the matrix-doubling algorithm.
Equivalent to MATLAB's dlyap(A', Q).
"""
function local_dlyap(A::AbstractMatrix{<:Real}, Q::AbstractMatrix{<:Real};
                     maxiter::Int=100, tol::Real=1e-12)
    P  = copy(Q)
    Ai = copy(A)
    for _ in 1:maxiter
        P_new = Ai * P * Ai' + P
        err   = norm(P_new - P, Inf) / (norm(P, Inf) + 1e-14)
        P     = (P_new + P_new') / 2
        Ai    = Ai * Ai
        err < tol && break
    end
    return (P + P') / 2
end


# =========================================================================== #
#  Misc                                                                        #
# =========================================================================== #

ternary_str(cond::Bool, s_true::String, s_false::String) = cond ? s_true : s_false


# =========================================================================== #
#  HP-filtered covariance — fast sub-matrix version                           #
#                                                                              #
#  For the first-order state-space y_t = T·s_t, s_t = A·s_{t-1} + B·ε_t,   #
#  the HP-filtered covariance is:                                              #
#    Var_HP = ∫₀^π |1-H(ω)|² · G(ω)·B_Σ_Bt·G(ω)' · dω/π                   #
#  where G(ω) = T·(I - A e^{-iω})^{-1}  and  H(ω) = 1/(1+λ(2-2cos(ω))²).  #
#                                                                              #
#  SPEED: pass only the rows of T needed for the moments (~39 of 491).        #
#  Cost drops from ~25M flops/freq to ~1M flops/freq — a 25× speedup.        #
#                                                                              #
#  References: Burnside (1998, JMCB); Uhlig (1999)                            #
# =========================================================================== #

"""
    build_hp_weights(λ, nfreq) -> (w_var, w_lag1)

Pre-compute scalar HP-filter integration weights for variance and lag-1
autocovariance. Call once per estimation; reuse across evaluations.

  w_var[k]  = |1-H(ω_k)|² / nfreq   (variance accumulation weight)
  w_lag1[k] = w_var[k] * cos(ω_k)   (lag-1 autocovariance weight)
"""
function build_hp_weights(λ::Float64=1600.0, nfreq::Int=256)
    w_var  = Vector{Float64}(undef, nfreq)
    w_lag1 = Vector{Float64}(undef, nfreq)
    for k in 1:nfreq
        ω = π * k / nfreq
        gain_sq = (1.0 - 1.0 / (1.0 + λ * (2.0 - 2.0 * cos(ω))^2))^2
        w_var[k]  = gain_sq / nfreq
        w_lag1[k] = gain_sq * cos(ω) / nfreq
    end
    return w_var, w_lag1
end

"""
    hp_filtered_cov_fast(A, B_Σ_Bt, T_sub, R_sub_Σe_Rsub, w_var, w_lag1)
      -> (Γ_hp, Γ1_hp)

Compute HP-filtered variance and lag-1 autocovariance for a SUB-SET of
endogenous variables in a single frequency loop.

Arguments:
  A             : state transition (n_state × n_state)
  B_Σ_Bt        : B·Σe·B' (n_state × n_state)
  T_sub         : observation rows for needed variables (n_needed × n_state)
  R_sub_Σe_Rsub : R[needed,:]·Σe·R[needed,:]' (n_needed × n_needed)
  w_var, w_lag1 : pre-computed HP weights from build_hp_weights()

Returns:
  Γ_hp  (n_needed × n_needed) — HP-filtered variance-covariance
  Γ1_hp (n_needed × n_needed) — HP-filtered lag-1 autocovariance
"""
function hp_filtered_cov_fast(A::AbstractMatrix{Float64},
                               B_Σ_Bt::Matrix{Float64},
                               T_sub::Matrix{Float64},
                               R_sub_Σe_Rsub::Matrix{Float64},
                               w_var::Vector{Float64},
                               w_lag1::Vector{Float64})
    n_state  = size(A, 1)
    n_needed = size(T_sub, 1)
    nfreq    = length(w_var)

    I_s = Matrix{ComplexF64}(I, n_state, n_state)
    A_c = Matrix{ComplexF64}(A)     # complex copy, reused each frequency

    Γ_hp  = zeros(n_needed, n_needed)
    Γ1_hp = zeros(n_needed, n_needed)

    # Pre-allocate complex workspace to avoid allocations in the loop
    M     = Matrix{ComplexF64}(undef, n_state, n_state)
    G     = Matrix{ComplexF64}(undef, n_needed, n_state)   # T_sub * Minv
    GB    = Matrix{ComplexF64}(undef, n_needed, n_state)   # G * B_Σ_Bt
    S_y_c = Matrix{ComplexF64}(undef, n_needed, n_needed)  # GB * G'

    for k in 1:nfreq
        ω   = π * k / nfreq
        eiω = exp(-im * ω)

        # M = I - A * e^{-iω}
        @inbounds for j in 1:n_state, i in 1:n_state
            M[i, j] = I_s[i, j] - A_c[i, j] * eiω
        end
        Minv = M \ I_s   # 78×78 complex linear solve

        # G = T_sub * Minv  (n_needed × n_state)
        mul!(G, T_sub, Minv)

        # S_y = G * B_Σ_Bt * G'  (n_needed × n_needed)
        mul!(GB, G, B_Σ_Bt)
        mul!(S_y_c, GB, G')
        S_y = real.(S_y_c)   # discard imaginary noise

        # Accumulate weighted contributions
        @inbounds for j in 1:n_needed, i in 1:n_needed
            Γ_hp[i, j]  += w_var[k]  * S_y[i, j]
            Γ1_hp[i, j] += w_lag1[k] * S_y[i, j]
        end
    end

    # Frequency-flat contemporaneous contribution (R·Σe·R')
    hp_flat  = sum(w_var)
    hp_flat1 = sum(w_lag1)
    @inbounds for j in 1:n_needed, i in 1:n_needed
        Γ_hp[i, j]  += hp_flat  * R_sub_Σe_Rsub[i, j]
        Γ1_hp[i, j] += hp_flat1 * R_sub_Σe_Rsub[i, j]
    end

    Γ_hp  = (Γ_hp  .+ Γ_hp')  ./ 2
    Γ1_hp = (Γ1_hp .+ Γ1_hp') ./ 2
    return Γ_hp, Γ1_hp
end


# =========================================================================== #
#  SHARED SMM DEFINITIONS (moved from smm_estimation.jl, 2026-07-10)          #
# =========================================================================== #
# Single source of truth for the θ layout, moment layout, weighting matrix,
# and the human-readable fit/parameter reports. Included by BOTH
# run_smm_estimation.jl (via utils.jl) and main_SOE_gap.jl, so the fit table
# printed after a model solve is the SAME objective the estimator minimizes.
# Do NOT redefine any of these elsewhere.
#
# Include guard: utils.jl is included by several files (run_smm_estimation.jl,
# smm_model_moments.jl, main_SOE_gap.jl, shock-analysis scripts), so this
# section can be reached more than once per session — skip const redefinition.
if !@isdefined(_SMM_SHARED_DEFS_LOADED)
const _SMM_SHARED_DEFS_LOADED = true

# ---- Estimation output folder (2026-07-10) --------------------------------- #
# ALL estimation outputs (checkpoint, estimates, results, progress log,
# best_sol.txt, min_loss.txt, inference) live here — NOT in Data/, which holds
# inputs only. @__DIR__ = julia_dynare/, so the path is identical locally and
# inside the cluster bundle; copy this folder back from the cluster and
# main_SOE_gap.jl picks up the newest θ automatically.
const ESTIMATION_DIR = joinpath(@__DIR__, "estimation_results")

# ---- θ layout (36 parameters) --------------------------------------------- #
#   θ[1] ilabcosts  θ[2] epsY  θ[3] epsM  θ[4] log(kappaV)  θ[5] rho_om
#   θ[6] rho_A      θ[7:18] isigma_tfp_1:12   θ[19:30] sigma_om_1:12
#   θ[31] rho_pvstar θ[32] sigma_pvstar θ[33] rho_xi θ[34] sigma_xi
#   θ[35] etastar   θ[36] kappaw (0 = flexible wages; added 2026-07-08)
const PARAM_LABELS = vcat(
    ["ilabcosts", "epsY", "epsM", "log(kappaV)", "rho_om", "rho_A"],
    ["isigma_tfp_$(i)" for i in 1:12],
    ["sigma_om_$(i)" for i in 1:12],
    ["rho_pvstar", "sigma_pvstar", "rho_xi", "sigma_xi"],
    ["etastar"],
    ["kappaw"],
)
const N_THETA = length(PARAM_LABELS)   # 36

# CSV names (underscore style) — smm_checkpoint.csv / smm_estimates.csv are
# read BY NAME in main_SOE_gap.jl (est["log_kappaV"], est["kappaw"], ...).
const CSV_PARAM_NAMES = vcat(
    ["ilabcosts","epsY","epsM","log_kappaV","rho_om","rho_A"],
    ["isigma_tfp_$(i)" for i in 1:12],
    ["sigma_om_$(i)" for i in 1:12],
    ["rho_pvstar","sigma_pvstar","rho_xi","sigma_xi","etastar","kappaw"])

# Shock AR(1) persistences are bounded to [0, 1): non-negative (rules out
# oscillatory structural shocks) and < 1 for stationarity — the support of the
# Beta priors used for persistences in estimated (SOE-)DSGE models (Garcia-Cicco,
# Pancrazi & Uribe 2010 AER; Smets & Wouters 2007; BCCh XMAS). The persistences
# rho_om, rho_A (theta 5,6) and rho_pvstar, rho_xi (theta 31,33) all carry LB >= 0.
const LB = [1e-3; 0.30; 0.05; log(1e3);   0.00;  0.10;
            fill(1e-4, 12);
            fill(1e-5, 12);
            0.50;  0.005; 0.00; 0.0;  0.50;
            0.0]      # kappaw ≥ 0 (0 = flexible wages)
const UB = [50.0; 1.50; 0.50; log(1e8);   0.99;  0.99;
            fill(0.10, 12);
            fill(0.20, 12);
            0.99;  0.20;  0.99; 0.05; 6.00;
            400.0]    # kappaw ≤ 400 (≈ 7q Calvo duration at epsw = 10)

# ---- Moment layout (60 moments) ------------------------------------------- #
const N_MOMENTS = 60
const MOMENT_NAMES = vcat(
    ["std(Y_$(i))"  for i in 1:12], ["std(PH_$(i))" for i in 1:12],
    ["std(L_$(i))"  for i in 1:12],
    ["std(GDP)", "std(pi)", "corr(GDP,pi)", "std(TB/GDP)",
     "std(Q)", "autocorr(Q)", "corr(GDP,Q)",
     "rank corr: output (model vs data)", "rank corr: prices (model vs data)",
     "rank corr: labor  (model vs data)"],
    ["corr(Y_$(i),PH_$(i))" for i in 1:12],
    ["corr(N,GDP)", "corr(N,GDP/N)"])

const MOMENT_BLOCKS = [
    (1:12,  "std(Y_i) sectoral output vol"),
    (13:24, "std(PH_i) sectoral price vol"),
    (25:36, "std(L_i) sectoral labor vol"),
    (37:43, "aggregates (GDP, pi, TB, Q)"),
    (44:46, "rank correlations"),
    (47:58, "corr(Y_i,PH_i) supply/demand mix"),
    (59:60, "labor comovement corr(N,·)"),
]

# ---- Weighting matrix ------------------------------------------------------ #
function build_weighting_matrix(dm::Vector{<:Real})
    w = ones(N_MOMENTS)
    # 1:36 sectoral stds + 37,38,40,41 aggregate stds: inverse-squared data
    # value (percent-error metric, scale-free across moments of different size)
    for k in vcat(1:36, [37, 38, 40, 41])
        d = abs(dm[k]); w[k] = d > 1e-4 ? 1.0/d^2 : 1.0/0.01^2
    end
    w[39] *= 0.20     # corr(GDP,π): structurally hard for supply-shock model
    w[42]  = 2.0      # autocorr(Q): identifies rho_pvstar
    w[44]  = 2.0; w[45] = 2.0; w[46] = 2.0   # rank correlations: moderate
    # corr(Y_i,PH_i): FIXED weight (2026-07-09). Old proportional 1.5/d²
    # exploded for near-zero data correlations (sector 10: w≈30,800) and made
    # this block 99.5% of the objective. Correlations are bounded [-1,1] →
    # fixed weight, 1.5× the rank weight to keep identification emphasis.
    for k in 47:58
        w[k] = 3.0
    end
    w[59] = 2.0; w[60] = 2.0   # corr(N,GDP), corr(N,GDP/N)
    return Diagonal(w) |> Matrix
end

# ---- Report printers ------------------------------------------------------- #
function print_param_table(θ::AbstractVector; io=stdout)
    @printf(io, "\n  %-3s %-16s %12s %10s %10s  %s\n",
            "#", "Parameter", "Value", "LB", "UB", "Bound?")
    println(io, "  ", repeat("-", 66))
    for k in 1:N_THETA
        span_k = UB[k] - LB[k]
        flag = θ[k] <= LB[k] + 0.02*span_k ? "<< at LB" :
               θ[k] >= UB[k] - 0.02*span_k ? ">> at UB" : ""
        @printf(io, "  %-3d %-16s %12.4f %10.3f %10.3f  %s\n",
                k, PARAM_LABELS[k], θ[k], LB[k], UB[k], flag)
    end
    println(io, "  ", repeat("-", 66))
    println(io, "  'at LB/UB' = within 2% of a bound: not identified there, or bound binds.")
end

function print_fit_table(dm::AbstractVector, mm::AbstractVector, W::AbstractMatrix; io=stdout)
    ψ  = dm .- mm
    wd = [W[i,i]*ψ[i]^2 for i in 1:N_MOMENTS]
    tot = sum(wd)
    @printf(io, "\n  %-34s %9s %9s %9s %10s %6s\n",
            "Moment", "Data", "Model", "Diff", "W*Diff2", "%obj")
    println(io, "  ", repeat("-", 84))
    for (rng, lbl) in MOMENT_BLOCKS
        bsum = sum(wd[rng])
        @printf(io, "  -- %-48s block %8.3f  %5.1f%% --\n", lbl, bsum, 100bsum/tot)
        for i in rng
            @printf(io, "  %-34s %9.5f %9.5f %+9.5f %10.4f %5.1f%%\n",
                    MOMENT_NAMES[i], dm[i], mm[i], ψ[i], wd[i], 100wd[i]/tot)
        end
    end
    println(io, "  ", repeat("-", 84))
    @printf(io, "  %-34s %29s %10.4f %6s\n", "TOTAL OBJECTIVE", "", tot, "100%")
end

end  # include guard (_SMM_SHARED_DEFS_LOADED)
