"""
utils.jl
========
Helper functions for the NK-IOSOE Julia/Dynare.jl pipeline.

Contents:
  - write_params_mod   : generate params_jl.mod (read by NK_SOE_lev_gap2.mod)
  - safe_spearman      : Spearman corr that returns 0 when model vec is uniform
  - local_dlyap        : discrete Lyapunov solver (doubling algorithm)
  - ternary_str        : conditional string helper
"""

using LinearAlgebra, StatsBase, Printf

# =========================================================================== #
#  params_jl.mod generator                                                     #
#                                                                              #
#  NK_SOE_lev_gap2.mod does  @#include "params_jl.mod"  instead of the        #
#  old  load params_val_ul.mat.  This function writes that file with every     #
#  parameter value pre-expanded, so Dynare.jl never needs MATLAB or Octave.   #
# =========================================================================== #

"""
    write_params_mod(mod_dir, p) -> String

Generate `mod_dir/params_jl.mod` containing explicit Dynare parameter
assignments for all scalars, sectoral vectors and the IO matrix.

Arguments:
  mod_dir  : directory that contains NK_SOE_lev_gap2.mod
  p        : NamedTuple or Dict with all computed steady-state values

The returned string is the path to the written file.
"""
function write_params_mod(mod_dir::String, p::NamedTuple)
    path = joinpath(mod_dir, "params_jl.mod")
    nsec = p.nsec

    # MODEL-DEFINING FIELDS MUST BE PRESENT (2026-08-20).
    #
    # These used to fall back to a default via hasproperty(), which meant a
    # caller that had not been updated silently built a DIFFERENT MODEL and said
    # nothing: subsMC -> 1.0 removed the LPR markup subsidy, modGi -> 0 removed
    # government consumption entirely, modtfpY -> 1 put mining's TFP back into
    # its production function. oil_shock_analysis.jl was in exactly that state.
    # Fail loudly instead — a missing field is always a caller that needs
    # updating, never something to paper over.
    for fld in (:subsMC_val, :modGi, :modtfpY, :gshare_target,
                :modalphaK, :modKbar, :modchiI, :modRKss, :nuK_val, :PIinv_ss_val)
        hasproperty(p, fld) || error("""
            write_params_mod: params NamedTuple is missing `$(fld)`.
            This field defines the model, so it cannot be defaulted. The caller
            predates a model change — add it there. Callers that build params:
            main_SOE_gap.jl and oil_shock_analysis.jl.
            """)
    end

    open(path, "w") do io
        println(io, "// -------------------------------------------------------")
        println(io, "// params_jl.mod  —  auto-generated by main_SOE_gap.jl")
        println(io, "// Do NOT edit manually; re-run main_SOE_gap.jl to refresh.")
        println(io, "// -------------------------------------------------------")
        println(io)

        # ---- Scalar structural parameters -------------------------------- #
        _wp(io, "sigma_i",      p.sigma_i_val)
        _wp(io, "sigma_L_agg",  p.sigma_L_agg_val)
        _wp(io, "ilabcosts",    p.ilabcosts_val)
        _wp(io, "gamma",        p.gamma_val)
        _wp(io, "psi",          get(p, :psi_val, 1.5))
        # GHH disutility scale chi0 = chi_weight * C_ss^gamma (holds SS at KPR
        # values). Falls back to C_ss^gamma (chi_weight = 1) if not supplied.
        _wp(io, "chi0",         get(p, :chi0_val, p.C_ss^p.gamma_val))
        _wp(io, "beta",         p.beta_val)
        _wp(io, "phi",          p.phi_val)
        _wp(io, "epsilon",      10.0)
        _wp(io, "rho",          p.rho_val)
        _wp(io, "rho_om1",      p.rho_om1_val)
        # rho_tfp1 accepts a scalar (common TFP persistence) or an nsec-vector
        # (sector-specific, e.g. transitory agriculture shock with half-life of
        # half a quarter → ρ = 0.25).  The lev mod uses the sectoral parameters
        # rho_tfp1_<i> (written in the loop below); the scalar alias is kept for
        # the SMM mod, whose equations use the common rho_tfp1.  When a vector
        # is passed, the alias takes the LAST entry (an unshocked sector =
        # common persistence) — it is unused by the lev mod in that case.
        _rho_tfp1_vec = p.rho_tfp1_val isa AbstractVector ?
            collect(Float64, p.rho_tfp1_val) : fill(Float64(p.rho_tfp1_val), p.nsec)
        _wp(io, "rho_tfp1",     _rho_tfp1_vec[end])
        _wp(io, "rho_tfp2",     p.rho_tfp2_val)
        _wp(io, "rhoi",         0.5)          # rhoi = 0.5 + 0*rhoi_val
        _wp(io, "rhoirule",     p.rhoirule_val)
        _wp(io, "ombar",        p.ombar_val)
        _wp(io, "phi_b",       p.phi_b_val)
        _wp(io, "bbar",         p.bbar_val)
        _wp(io, "epsilonX",     p.epsilonX_val)
        _wp(io, "omegaX",       p.omegaX_val)
        _wp(io, "ystar_ss",     p.ystar_ss_val)
        _wp(io, "etastar",      p.etastar_val)
        _wp(io, "epsilonV",     p.epsilonV_val)
        _wp(io, "kappaV",       p.kappaV_val)
        _wp(io, "sigmaH",       p.sigmaH_val)
        _wp(io, "Pistar_ss",    p.Pistar_ss_val)
        _wp(io, "PVstar_ss",    p.PVstar_ss_val)
        _wp(io, "rho_pvstar",   p.rho_pvstar_val)
        _wp(io, "sigma_pvstar", p.sigma_pvstar_val)
        _wp(io, "rho_zeta",       p.rho_zeta_val)
        _wp(io, "sigma_zeta",     p.sigma_zeta_val)
        _wp(io, "Rworld_ss",    p.Rworld_ss_val)
        # Sticky wages (Rotemberg wage PC). Defaults apply unless the driver
        # passes epsw_val / kappaw_val in the params NamedTuple.
        # kappaw default 115 ≈ Calvo wage duration of 4 quarters:
        # slope = (1-θw)(1-βθw)/θw = 0.0868 with θw=0.75, β=0.986 → κw = εw/slope.
        # kappaw = 0 → flexible wages (nests the pre-2026-07 model exactly).
        _wp(io, "epsw",   get(p, :epsw_val,   10.0))
        _wp(io, "kappaw", get(p, :kappaw_val, 115.0))
        # Oil sector scalar parameters
        _wp(io, "epsilonV_oil",    p.epsilonV_oil_val)
        _wp(io, "rho_postar",      p.rho_postar_val)
        _wp(io, "sigma_postar",    p.sigma_postar_val)
        _wp(io, "POstar_ss",       p.POstar_ss_val)
        _wp(io, "shock_eps_postar",p.shock_eps_postar_val)
        _wp(io, "rho_pc",         p.rho_pc_val)
        _wp(io, "sigma_pc",       p.sigma_pc_val)
        _wp(io, "Pcstar_ss",      p.Pcstar_ss_val)
        _wp(io, "shock_eps_pc",   p.shock_eps_pc_val)
        _wp(io, "Y2_ss",          p.Y2_ss_val)
        _wp(io, "X_cu_ss",        p.X_cu_ss_val)
        _wp(io, "phi_cu",         p.phi_cu_val)
        # LPR semi-fixed capital: nuK = 1/phi, the capital supply elasticity.
        _wp(io, "nuK",            p.nuK_val)
        _wp(io, "PIinv_ss",       p.PIinv_ss_val)
        # G/GDP target, carried so the estimation can re-solve the same SS.
        _wp(io, "gshare_target",  p.gshare_target)
        # LPR markup subsidy: (1-tau) factor on MC in the pricing condition.
        # 1.0 = no subsidy (markup eps/(eps-1)); (eps-1)/eps = LPR (markup 1).
        _wp(io, "subsMC",         p.subsMC_val)
        _wp(io, "Pi_cu_ss",       p.Pi_cu_ss_val)
        _wp(io, "PH2_ss",         p.PH2_ss_val)
        println(io)

        # ---- Steady-state scalars ---------------------------------------- #
        # pi_ss = 1 (zero net domestic inflation in SS)
        # r_ss = Pistar_ss / beta (from household Euler equation)
        _wp(io, "pi_ss",   1.0)
        _wp(io, "r_ss",    p.Pistar_ss_val / p.beta_val)
        _wp(io, "w_ss",    p.w_ss)
        _wp(io, "C_ss",    p.C_ss)
        _wp(io, "GDP_ss",  p.GDP_ss)
        _wp(io, "N_ss",    p.N_ss)
        _wp(io, "p_s_ss",  p.p_s_ss)
        _wp(io, "p_g_ss",  p.p_g_ss)
        _wp(io, "C_s_ss",  p.C_s_ss)
        _wp(io, "C_g_ss",  p.C_g_ss)
        _wp(io, "Bstar_ss",     p.Bstar_ss)
        _wp(io, "Q_ss",         p.Q_ss)
        _wp(io, "TB_ss",        p.TB_ss)
        _wp(io, "PX_ss",        p.PX_ss)
        _wp(io, "V_ss",         p.V_ss)
        _wp(io, "CF_ss",        p.CF_ss)
        _wp(io, "CFg_total_ss", p.CFg_total_ss)
        _wp(io, "CFs_total_ss", p.CFs_total_ss)
        _wp(io, "IMP_ss",     p.IMP_ss_val)
        _wp(io, "Ctot_ss",    p.Ctot_ss_val)
        _wp(io, "Ctotg_ss",   p.Ctotg_ss_val)
        _wp(io, "Ctots_ss",   p.Ctots_ss_val)
        _wp(io, "VA_ss",      p.VA_ss_val)
        _wp(io, "M_tot_ss",   p.M_tot_ss)
        _wp(io, "Y_ss",       p.Y_tot_ss)       # Y_ss ≡ Y_tot_ss
        println(io)

        # ---- Shock activation flags ------------------------------------- #
        println(io, "// Shock variances (0 = off, 1 = on; amplitude inside model equations)")
        _wp(io, "shock_eps_i",      p.shock_eps_i_val)
        _wp(io, "shock_eps_pvstar", p.shock_eps_pvstar_val)
        _wp(io, "shock_eps_zeta",     p.shock_eps_zeta_val)
        # NOTE: the per-sector activation flags shock_eps_om_i and std devs
        # sigma_om_i are written below. Do NOT write a scalar sigma_om /
        # rho_om2 — those parameters do not exist in NK_SOE_lev_gap2.mod and
        # Dynare would reject them.
        #
        # Goods/services demand-reallocation shock (2026-08-19). The aggregate
        # om_g shock was previously removed on the grounds that "demand is now
        # sectoral"; but the 12 sectoral taste shifters are normalised by
        # norm_g/norm_s to preserve the goods and services budgets, so they are
        # pure within-bundle reallocation and carry 0.1% of GDP variance. This
        # is FGI (2023 JME) omega_t, calibrated off the observable goods
        # expenditure share — see Data/build_reallocation_calibration.py.
        _wp(io, "rho_omg",          p.rho_omg_val)
        _wp(io, "sigma_omg",        p.sigma_omg_val)
        _wp(io, "shock_eps_omg",    p.shock_eps_omg_val)
        println(io)

        # ---- Option-A: 12 sectoral demand shock parameters -------------- #
        println(io, "// Option-A: sectoral demand shock std devs and activation flags")
        for i in 1:nsec
            _wp(io, "sigma_om_$(i)",     p.sigma_om_vec[i])
        end
        for i in 1:nsec
            _wp(io, "shock_eps_om_$(i)", p.shock_eps_om_vec[i])
        end
        println(io)

        # ---- Sectoral parameters (i = 1..nsec) -------------------------- #
        println(io, "// Sectoral parameters")
        for i in 1:nsec
            _wp(io, "gammag_$(i)",       p.modgammag[i])
            _wp(io, "gammas_$(i)",       p.modgammas[i])
            _wp(io, "alpha_$(i)",        p.modalpha[i])
            _wp(io, "epsY_$(i)",         p.modepsY[i])
            _wp(io, "epsM_$(i)",         p.modepsM[i])
            _wp(io, "kappa_$(i)",        p.modkappa[i])
            _wp(io, "dummyg_$(i)",       Float64(p.goods[i]))
            _wp(io, "dummys_$(i)",       Float64(p.services[i]))
            _wp(io, "cl_$(i)",           p.modcl[i])
            _wp(io, "clneg_$(i)",        p.modclneg[i])
            _wp(io, "cm_$(i)",           p.modcm[i])
            _wp(io, "chiX_$(i)",         p.modchiX[i])
            _wp(io, "alphaV_$(i)",       p.modalphaV[i])
            # LPR semi-fixed capital: share, endowment, investment weight, SS rental.
            _wp(io, "alphaK_$(i)",       p.modalphaK[i])
            _wp(io, "Kbar_$(i)",         p.modKbar[i])
            _wp(io, "chiI_$(i)",         p.modchiI[i])
            _wp(io, "RKss_$(i)",         p.modRKss[i])
            _wp(io, "varrho_$(i)",       p.modvarrho[i])
            _wp(io, "isigma_tfp_$(i)",   p.isigma_tfp_val[i])
            _wp(io, "rho_tfp1_$(i)",     _rho_tfp1_vec[i])
            _wp(io, "shock_epsA_$(i)",   p.shock_epsA_val[i])
            _wp(io, "alphaOilShare_$(i)", p.modalphaOil[i])
            # tfpY_i = 0 for mining only — see the note in NK_SOE_lev_gap2.mod.
            _wp(io, "tfpY_$(i)", p.modtfpY[i])
            # Exogenous real government consumption of sector i's output.
            _wp(io, "Gi_$(i)", p.modGi[i])
            _wp(io, "PIV_ss$(i)",         p.PIV_ss_vec[i])
            # Sectoral steady-state scalars (indexed, referenced in initval block)
            _wp(io, "PL_ss$(i)",  p.PL_ss[i])
            _wp(io, "CFg_ss$(i)", p.CFg_ss[i])
            _wp(io, "CFs_ss$(i)", p.CFs_ss[i])
            _wp(io, "CHg_ss$(i)", p.CHg_ss[i])
            _wp(io, "CHs_ss$(i)", p.CHs_ss[i])
            _wp(io, "Vi_ss$(i)",  p.Vi_ss[i])
            _wp(io, "PH_ss$(i)",  p.pH_ss[i])
            _wp(io, "MC_ss$(i)",  p.MCi_ss[i])
            _wp(io, "Y_ss$(i)",   p.Yi_ss[i])
            _wp(io, "L_ss$(i)",   p.L_ss[i])
            _wp(io, "Cgi_ss$(i)", p.C_gi_ss[i])
            _wp(io, "Csi_ss$(i)", p.C_si_ss[i])
            _wp(io, "P_ss$(i)",   p.P_ss[i])
            _wp(io, "PMi_ss$(i)", p.PMi_ss[i])
            _wp(io, "Mi_ss$(i)",  p.M_ss[i])
            println(io)
        end

        # ---- IO matrix (beta_i_j for i,j = 1..nsec) --------------------- #
        println(io, "// IO matrix: beta_i_j = share of inputs sector i sources from sector j")
        for i in 1:nsec, j in 1:nsec
            _wp(io, "beta_$(i)_$(j)", p.modbeta[i, j])
        end
    end

    return path
end

# Internal helper: write one Dynare parameter assignment
function _wp(io::IO, name::String, val::Real)
    # Use full precision; avoid scientific notation for very small/large values
    @printf io "%s = %.15g;\n" name val
end


# =========================================================================== #
#  Rank correlation                                                            #
# =========================================================================== #

"""
    safe_spearman(x, y) -> Float64

Spearman rank correlation. Returns 0.0 when `x` is nearly uniform (model std
devs identical across sectors), matching the smm_model_moments.m behaviour.
"""
function safe_spearman(x::AbstractVector{<:Real}, y::AbstractVector{<:Real})
    std(x) < 1e-12 * (abs(mean(x)) + 1e-12) && return 0.0
    return corspearman(x, y)
end


# =========================================================================== #
#  Discrete Lyapunov equation                                                  #
# =========================================================================== #

"""
    local_dlyap(A, Q) -> P

Solve  P = A P Aᵀ + Q  by the matrix-doubling algorithm.
Equivalent to MATLAB's dlyap(A', Q).
"""
function local_dlyap(A::AbstractMatrix{<:Real}, Q::AbstractMatrix{<:Real};
                     maxiter::Int=100, tol::Real=1e-12)
    P  = copy(Q)
    Ai = copy(A)
    for _ in 1:maxiter
        P_new = Ai * P * Ai' + P
        err   = norm(P_new - P, Inf) / (norm(P, Inf) + 1e-14)
        P     = (P_new + P_new') / 2
        Ai    = Ai * Ai
        err < tol && break
    end
    return (P + P') / 2
end


# =========================================================================== #
#  Misc                                                                        #
# =========================================================================== #

ternary_str(cond::Bool, s_true::String, s_false::String) = cond ? s_true : s_false


# =========================================================================== #
#  HP-filtered covariance — fast sub-matrix version                           #
#                                                                              #
#  For the first-order state-space y_t = T·s_t, s_t = A·s_{t-1} + B·ε_t,   #
#  the HP-filtered covariance is:                                              #
#    Var_HP = ∫₀^π |1-H(ω)|² · G(ω)·B_Σ_Bt·G(ω)' · dω/π                   #
#  where G(ω) = T·(I - A e^{-iω})^{-1}  and  H(ω) = 1/(1+λ(2-2cos(ω))²).  #
#                                                                              #
#  SPEED: pass only the rows of T needed for the moments (~39 of 491).        #
#  Cost drops from ~25M flops/freq to ~1M flops/freq — a 25× speedup.        #
#                                                                              #
#  References: Burnside (1998, JMCB); Uhlig (1999)                            #
# =========================================================================== #

"""
    build_hp_weights(λ, nfreq) -> (w_var, w_lag1)

Pre-compute scalar HP-filter integration weights for variance and lag-1
autocovariance. Call once per estimation; reuse across evaluations.

  w_var[k]  = |1-H(ω_k)|² / nfreq   (variance accumulation weight)
  w_lag1[k] = w_var[k] * cos(ω_k)   (lag-1 autocovariance weight)
"""
function build_hp_weights(λ::Float64=1600.0, nfreq::Int=256)
    w_var  = Vector{Float64}(undef, nfreq)
    w_lag1 = Vector{Float64}(undef, nfreq)
    for k in 1:nfreq
        ω = π * k / nfreq
        gain_sq = (1.0 - 1.0 / (1.0 + λ * (2.0 - 2.0 * cos(ω))^2))^2
        w_var[k]  = gain_sq / nfreq
        w_lag1[k] = gain_sq * cos(ω) / nfreq
    end
    return w_var, w_lag1
end

"""
    hp_filtered_cov_fast(A, B_Σ_Bt, T_sub, R_sub_Σe_Rsub, w_var, w_lag1)
      -> (Γ_hp, Γ1_hp)

Compute HP-filtered variance and lag-1 autocovariance for a SUB-SET of
endogenous variables in a single frequency loop.

Arguments:
  A             : state transition (n_state × n_state)
  B_Σ_Bt        : B·Σe·B' (n_state × n_state)
  T_sub         : observation rows for needed variables (n_needed × n_state)
  R_sub_Σe_Rsub : R[needed,:]·Σe·R[needed,:]' (n_needed × n_needed)
  w_var, w_lag1 : pre-computed HP weights from build_hp_weights()

Returns:
  Γ_hp  (n_needed × n_needed) — HP-filtered variance-covariance
  Γ1_hp (n_needed × n_needed) — HP-filtered lag-1 autocovariance
"""
function hp_filtered_cov_fast(A::AbstractMatrix{Float64},
                               B_Σ_Bt::Matrix{Float64},
                               T_sub::Matrix{Float64},
                               R_sub_Σe_Rsub::Matrix{Float64},
                               w_var::Vector{Float64},
                               w_lag1::Vector{Float64})
    n_state  = size(A, 1)
    n_needed = size(T_sub, 1)
    nfreq    = length(w_var)

    I_s = Matrix{ComplexF64}(I, n_state, n_state)
    A_c = Matrix{ComplexF64}(A)     # complex copy, reused each frequency

    Γ_hp  = zeros(n_needed, n_needed)
    Γ1_hp = zeros(n_needed, n_needed)

    # Pre-allocate complex workspace to avoid allocations in the loop
    M     = Matrix{ComplexF64}(undef, n_state, n_state)
    G     = Matrix{ComplexF64}(undef, n_needed, n_state)   # T_sub * Minv
    GB    = Matrix{ComplexF64}(undef, n_needed, n_state)   # G * B_Σ_Bt
    S_y_c = Matrix{ComplexF64}(undef, n_needed, n_needed)  # GB * G'

    for k in 1:nfreq
        ω   = π * k / nfreq
        eiω = exp(-im * ω)

        # M = I - A * e^{-iω}
        @inbounds for j in 1:n_state, i in 1:n_state
            M[i, j] = I_s[i, j] - A_c[i, j] * eiω
        end
        Minv = M \ I_s   # 78×78 complex linear solve

        # G = T_sub * Minv  (n_needed × n_state)
        mul!(G, T_sub, Minv)

        # S_y = G * B_Σ_Bt * G'  (n_needed × n_needed)
        mul!(GB, G, B_Σ_Bt)
        mul!(S_y_c, GB, G')
        S_y = real.(S_y_c)   # discard imaginary noise

        # Accumulate weighted contributions
        @inbounds for j in 1:n_needed, i in 1:n_needed
            Γ_hp[i, j]  += w_var[k]  * S_y[i, j]
            Γ1_hp[i, j] += w_lag1[k] * S_y[i, j]
        end
    end

    # Frequency-flat contemporaneous contribution (R·Σe·R')
    hp_flat  = sum(w_var)
    hp_flat1 = sum(w_lag1)
    @inbounds for j in 1:n_needed, i in 1:n_needed
        Γ_hp[i, j]  += hp_flat  * R_sub_Σe_Rsub[i, j]
        Γ1_hp[i, j] += hp_flat1 * R_sub_Σe_Rsub[i, j]
    end

    Γ_hp  = (Γ_hp  .+ Γ_hp')  ./ 2
    Γ1_hp = (Γ1_hp .+ Γ1_hp') ./ 2
    return Γ_hp, Γ1_hp
end


# =========================================================================== #
#  SHARED SMM DEFINITIONS (moved from smm_estimation.jl, 2026-07-10)          #
# =========================================================================== #
# Single source of truth for the θ layout, moment layout, weighting matrix,
# and the human-readable fit/parameter reports. Included by BOTH
# run_smm_estimation.jl (via utils.jl) and main_SOE_gap.jl, so the fit table
# printed after a model solve is the SAME objective the estimator minimizes.
# Do NOT redefine any of these elsewhere.
#
# Include guard: utils.jl is included by several files (run_smm_estimation.jl,
# smm_model_moments.jl, main_SOE_gap.jl, shock-analysis scripts), so this
# section can be reached more than once per session — skip const redefinition.
if !@isdefined(_SMM_SHARED_DEFS_LOADED)
const _SMM_SHARED_DEFS_LOADED = true

# ---- Estimation output folder (2026-07-10) --------------------------------- #
# ALL estimation outputs (checkpoint, estimates, results, progress log,
# best_sol.txt, min_loss.txt, inference) live here — NOT in Data/, which holds
# inputs only. @__DIR__ = julia_dynare/, so the path is identical locally and
# inside the cluster bundle; copy this folder back from the cluster and
# main_SOE_gap.jl picks up the newest θ automatically.
const ESTIMATION_DIR = joinpath(@__DIR__, "estimation_results")

# SMM_TAG suffixes the result files, so a parameter sweep does not overwrite
# itself: SMM_TAG=epsY0.90 writes smm_estimates_epsY0.90.csv etc. The checkpoint
# is deliberately NOT tagged — it stays the single warm-start source.
const SMM_TAG = let t = get(ENV, "SMM_TAG", ""); isempty(t) ? "" : "_" * t end
tagged(fname::AbstractString) = let (b, e) = splitext(fname); b * SMM_TAG * e end

# ---- θ layout (36 parameters) --------------------------------------------- #
#   θ[1] ilabcosts  θ[2] epsY  θ[3] epsM  θ[4] log(kappaV)  θ[5] rho_om
#   θ[6] rho_A      θ[7:18] isigma_tfp_1:12   θ[19:30] sigma_om_1:12
#   θ[31] rho_pvstar θ[32] sigma_pvstar θ[33] rho_zeta θ[34] sigma_zeta
#   θ[35] etastar   θ[36] kappaw (0 = flexible wages; added 2026-07-08)
#   θ[37] lambda_A  θ[38] lambda_om  (shock-mix scales; added 2026-08-20)
#
# SHOCK-MIX SCALES (θ[37:38]). The 24 sectoral shock sizes θ[7:30] are PINNED at
# their data-measured values (sectoral_shock_calibration.csv), which fixes both
# the cross-sectional pattern AND the supply/demand balance. That left the
# corr(Y_i,PH_i) block — 40% of the objective — with no free parameter acting on
# it: the model produced negative corr(Y_i,PH_i) in 10 of 12 sectors (pure TFP
# signature) against data that are mixed, and construction strongly positive
# (+0.48 data vs -0.29 model, the single largest moment miss).
#
# lambda_A and lambda_om multiply the measured isigma_tfp and sigma_om vectors.
# They free exactly two margins — the overall scale of sectoral shocks, and the
# supply/demand MIX — while leaving the measured CROSS-SECTIONAL pattern intact,
# which is what the rank-correlation moments discipline. Identification:
# std(Y_i) pins the level, corr(Y_i,PH_i) pins the mix.
"""
Sector-specific TFP persistence: OPT-IN, default OFF (2026-08-24).

`SMM_SECTORAL_RHO=1` pins the twelve measured rho_hat_{A,i} and makes θ[6] the
exponent scale lambda_rho. Default OFF restores the single common rho_A.

Defined HERE, above PARAM_LABELS and LB/UB, because all three switch on it.

TESTED AND REJECTED, kept as a robustness exercise. Measured persistences
(idiosyncratic cycle) run 0.10-0.89, mean 0.51, against a freely-estimated common
rho_A of 0.983 — so the data's sectoral autocorrelations really are dispersed.
But the fit gets WORSE, in two independent parameterizations:

  common rho_A                    obj 6.738   ACsec 1.273   rbar 0.413
  sector-specific, multiplicative obj 8.176   ACsec 1.629   rbar 0.592
  sector-specific, power          obj 7.096   ACsec 1.452   rbar 0.474

In BOTH, lambda_rho ran hard to its upper bound (2.0, then 6.0), compressing the
cross-sectional SD from 0.258 to 0.086 and pushing every sector back toward the
common value. The power map cannot clamp and preserves ordering, so the second
run had every chance to keep the heterogeneity and declined.

Most likely reason: rho_hat is measured on an HP-filtered residual with the
persistent common factor projected out, and both operations strip persistence, so
0.51 understates the shock's. The rival explanation — that the dispersion in the
data's autocorr(Y_i) comes from network position, capital and price stickiness
rather than from shock persistence — cannot be separated with this measurement.
"""
const SECTORAL_RHO = get(ENV, "SMM_SECTORAL_RHO", "0") != "0"

const PARAM_LABELS = vcat(
    # θ[1] drives cl_i, the sectoral labour adjustment cost = FGI (2023 JME)
    # hiring cost c (their estimate 19.1, s.e. 12.6). The CSV key stays
    # "ilabcosts" for back-compatibility with existing checkpoints; the display
    # label says what it actually is. See the note in smm_estimation.jl.
    # θ[6] became a SCALE on the twelve MEASURED sectoral persistences on
    # 2026-08-24 (it was the single common rho_A). Same back-compatibility trick
    # as θ[1]: the CSV key stays "rho_A" so existing checkpoints still load, the
    # display label says what it now means. lambda_rho = 1 reproduces the
    # measured values exactly. See RHO_A_MEASURED in smm_estimation.jl.
    ["cl (FGI hiring c)", "epsY", "epsM", "log(kappaV)", "rho_om",
     SECTORAL_RHO ? "lambda_rho (persist. scale)" : "rho_A"],
    ["isigma_tfp_$(i)" for i in 1:12],
    ["sigma_om_$(i)" for i in 1:12],
    ["rho_pvstar", "sigma_pvstar", "rho_zeta", "sigma_zeta"],
    ["etastar"],
    ["kappaw"],
    ["lambda_A (TFP scale)", "lambda_om (demand scale)"],
)
const N_THETA = length(PARAM_LABELS)   # 36

# CSV names (underscore style) — smm_checkpoint.csv / smm_estimates.csv are
# read BY NAME in main_SOE_gap.jl (est["log_kappaV"], est["kappaw"], ...).
const CSV_PARAM_NAMES = vcat(
    ["ilabcosts","epsY","epsM","log_kappaV","rho_om","rho_A"],
    ["isigma_tfp_$(i)" for i in 1:12],
    ["sigma_om_$(i)" for i in 1:12],
    ["rho_pvstar","sigma_pvstar","rho_zeta","sigma_zeta","etastar","kappaw"],
    ["lambda_A","lambda_om"])

# Shock AR(1) persistences are bounded to [0, 1): non-negative (rules out
# oscillatory structural shocks) and < 1 for stationarity — the support of the
# Beta priors used for persistences in estimated (SOE-)DSGE models (Garcia-Cicco,
# Pancrazi & Uribe 2010 AER; Smets & Wouters 2007; BCCh XMAS). The persistences
# rho_om, rho_A (theta 5,6) and rho_pvstar, rho_zeta (theta 31,33) all carry LB >= 0.
# epsY (theta2) pinned ~0.80 (Atalay 2017 eps_Q~0.84) and epsM (theta3) pinned ~0.10
# (Atalay eps_m~0.10, strong complementarity): FIXED, not estimated. Low elasticities
# keep sector-specific shocks from washing out through the network (Atalay 83%->21%).
# Tight band (not a point) avoids the span=0 division in the CMA-ES [0,1] rescaling.
# SECTORAL_RHO is defined ABOVE PARAM_LABELS — it gates the label, LB and UB of
# theta[6], and PARAM_LABELS is built first.

const LB = [1e-3; 0.50; 0.02; log(1e3);   0.00;  (SECTORAL_RHO ? 0.25 : 0.10);
            fill(1e-4, 12);
            fill(1e-5, 12);
            0.50;  0.005; 0.50; 0.0;  0.10;   # rho_zeta LB 0.00->0.50: demand shock is persistent (beta-prior convention; data autocorr(Q)=0.72)
            0.0;      # kappaw ≥ 0 (0 = flexible wages)
            0.10; 0.10]   # lambda_A, lambda_om: shock scales, 1.0 = measured values
const UB = [50.0; 1.50; 0.60; log(1e8);   0.99;  (SECTORAL_RHO ? 6.00 : 0.99);
            fill(0.10, 12);
            fill(0.20, 12);
            # sigma_zeta UB raised 0.05 -> 0.15 (2026-08-21). theta-hat sat
            # exactly on the old bound, which truncated the rho_zeta/sigma_zeta
            # ridge described above and made rho_zeta look unidentified. A
            # bound-hitting estimate carries no information either way; give it
            # room and let the moments choose. If sigma_zeta still pins at 0.15
            # the aggregate demand shock is doing too much work and the problem
            # is elsewhere in the shock mix.
            0.99;  0.20;  0.99; 0.15; 6.00;
            # kappaw UB raised 400 -> 1500 (2026-08-21). 400 was "≈ 7q Calvo
            # duration at epsw = 10"; theta-hat came back at 399.98, i.e. exactly
            # on it, in two consecutive runs. A parameter pinned at a bound is not
            # an estimate, so give it room and find out where it actually goes.
            #
            # Read the answer sceptically either way. Seven quarters is already
            # at the sticky end of the wage-rigidity literature, and the reason
            # the estimator wants more is visible in the fit: model std(L_i)
            # exceeds the data in most sectors, and wage stickiness is the only
            # instrument left that damps employment volatility across the board
            # once cl has done what it can. If kappaw settles near 1500 too, the
            # binding problem is the labour block, not the bound.
            1500.0;
            5.00; 5.00]   # lambda_A, lambda_om ≤ 5× the measured shock sizes

# ---- Moment layout (60 moments) ------------------------------------------- #
# 61 as of 2026-08-19: std(omG), the goods expenditure share, appended LAST.
# Appended rather than inserted into the aggregates block so that every
# existing index is unchanged — the block slices 1:12, 13:24, 25:36, 37:43,
# 44:46, 47:58, 59:60 are hardcoded in the decomposition printers in
# smm_estimation.jl and would all have shifted.
# Indices of the parameters actually SEARCHED by CMA-ES. The other 29 are
# pinned via SMM_PIN and are OVERRIDDEN inside smm_model_moments, so perturbing
# them cannot move the moments — any Jacobian column for a pinned parameter is
# identically zero. Promoted to a module-level const on 2026-08-19 so that
# smm_inference.jl uses the same list (it previously differenced all 36, which
# made the sandwich rank-deficient and returned std errors of exactly 0.0 with
# t = Inf for every parameter, and used dof = K-36 instead of K-7).
#   1 = cl (FGI hiring cost c)   4 = log(kappaV)   5 = rho_om   6 = rho_A
#  33 = rho_zeta   34 = sigma_zeta   36 = kappaw
# 2026-08-20: lambda_A (37) and lambda_om (38) added. Before that the estimator
# had no instrument for the supply/demand mix, so the corr(Y_i,PH_i) block —
# 40% of the objective — was structurally unimprovable.
# 2026-08-21: log(kappaV) (4) and rho_zeta (33) REMOVED from the free set.
# The pre-flight sensitivity scan reports
#     theta[4]  log(kappaV) : |d obj| = 1.8e-4
#     theta[33] rho_zeta    : |d obj| = 3.4e-4
# against 1.0e+1 for the lambdas and 4.5e-1 for cl. They are flat to four
# orders of magnitude — not identified by this moment set. Searching them
# spent 2 of 9 CMA-ES dimensions on noise and let log(kappaV) drift to its
# upper bound, which then has to be explained in the paper as if it meant
# something. Pinned at their interior seeds in smm_estimation.jl; because the
# objective is flat in both, the pinned VALUE is immaterial — but say so in the
# paper rather than reporting a bound-hitting "estimate".
#
# rho_zeta (33) was pinned in the same 2026-08-21 pass and then RESTORED to the
# free set later the same day. Its flatness was not a property of the parameter,
# it was two fixable defects in the objective:
#
#  (a) zeta enters the Euler equations ONLY as the ratio zeta(+1)/zeta
#      (NK_SOE_lev_gap2.mod lines 373 and 874), so the effective forcing on the
#      intertemporal margin is sigma_zeta*sqrt((1-rho)/(1+rho)) — STRONGLY
#      decreasing in rho. rho and sigma trade off along a ridge, and sigma_zeta
#      sat exactly ON its upper bound (0.05), so the estimator could not buy the
#      amplitude needed to move along it. The bound truncated the ridge and the
#      objective went flat. UB raised below.
#  (b) corr(GDP,pi), one of the two moments that speaks to rho_zeta, was
#      downweighted 5x on a mistaken premise (see build_weighting_matrix).
#      Restored to full weight.
#
# Fix the objective first, then decide whether a parameter is identified. If
# rho_zeta is still flat after a run with (a) and (b) repaired, pin it then —
# and pin it on evidence.
# epsM (3) BAND WIDENED 2026-08-22, 0.19-0.21 -> 0.02-0.60. Still PINNED, but
# theta0 is clamped to [LB,UB], so a sweep at SMM_EPSM=0.05 would silently have
# been clamped back to 0.19. Widen so the grid is reachable.
#
# WHY epsM IS NOW THE PARAMETER OF INTEREST. The variance decomposition of
# 2026-08-22 showed the excess cross-sectoral comovement (rbar 0.417 model vs
# 0.221 data) is generated by NETWORK PROPAGATION of the twelve independent
# sectoral TFP shocks — on their own they give rbar = 0.585, higher than the
# all-shocks total. epsY could never fix that because epsY is the elasticity in
# the M-vs-V-vs-L nest, i.e. substitution among a sector's own input TYPES.
# Substitution ACROSS the twelve supplying sectors inside the materials bundle
# is governed by epsM. At 0.20 a buyer cannot substitute away from a supplier
# whose price rises, so every shock passes through to every buyer.
#
# epsY (2) FREED 2026-08-21, band widened 0.78-0.82 -> 0.50-1.50.
#
# The rbar moment added in the same pass says the network propagates about twice
# too much comovement: model 0.411 against 0.221 in the data. Higher input
# substitution means less propagation, so rbar points directly at epsY, and rbar
# is the moment that was added to speak to it. Atalay's own benchmark eps_Q ~ 1
# sits comfortably inside the new band, so this is not an exotic range — the old
# [0.78, 0.82] was a pin dressed as a band.
#
# COST: epsY changes the steady state (SS input shares depend on it whenever
# PH_ss != 1, which is the case here), so every evaluation now triggers
# recompute_ss_cached!. Expect the run to slow down materially.
#
# epsM (3) stays PINNED at 0.20. One experiment, one hypothesis.
# SMM_FREE_EPSY=0 pins epsY at SMM_EPSY instead of estimating it. That is the
# fast path AND the better one: see the note below.
#
# PROFILING BEATS ESTIMATING HERE. epsY shifts the STEADY STATE, so estimating
# it inside CMA-ES forces a nonlinear SS re-solve on essentially every
# evaluation — the single-slot SS cache never hits, because candidates differ in
# epsY by tiny continuous amounts. Pin epsY instead and sweep it on a grid: the
# SS is then solved ONCE per grid point, the cache hits 100%, and each run costs
# exactly what the pre-epsY runs cost.
#
# It also produces a better object. A grid gives the objective PROFILE in epsY,
# which shows whether epsY is identified at all and is a figure worth putting in
# the paper — rather than a point estimate from a search that spent most of its
# budget re-solving steady states.
const FREE_THETA = get(ENV, "SMM_FREE_EPSY", "1") != "0" ?
    [1, 2, 5, 6, 33, 34, 36, 37, 38] :
    [1,    5, 6, 33, 34, 36, 37, 38]

# Which of the SMM_PIN-overridden scalars are actually free. The objective reads
# epsY/epsM out of SMM_PIN, NOT out of theta — so without these flags, adding an
# index to FREE_THETA would let CMA-ES move it while the model never saw the
# change. That is exactly the failure mode that froze the shock sizes in the
# Klein-cache bug; encode it once here rather than rediscovering it.
const _FREE_EPSY = 2 in FREE_THETA
const _FREE_EPSM = 3 in FREE_THETA

const N_MOMENTS = 84
const MOMENT_NAMES = vcat(
    ["std(Y_$(i))"  for i in 1:12], ["std(PH_$(i))" for i in 1:12],
    ["std(L_$(i))"  for i in 1:12],
    ["std(GDP)", "std(pi)", "corr(GDP,pi)", "std(TB/GDP)",
     "std(Q)", "autocorr(Q)", "corr(GDP,Q)",
     "rank corr: output (model vs data)", "rank corr: prices (model vs data)",
     "rank corr: labor  (model vs data)"],
    ["corr(Y_$(i),PH_$(i))" for i in 1:12],
    ["corr(N,GDP)", "corr(N,GDP/N)"],
    ["std(omG) goods expenditure share"],
    # 62-63 (2026-08-19): the goods-services relative price channel. This is how
    # Ferrante, Graves & Iacoviello (2023) identify their hiring cost c — "with
    # no hiring costs there would be no change in relative prices in response to
    # a demand reallocation shock". Two-sided in cl (too little => no response,
    # too much => overshoot), unlike every other moment here, all of which are
    # monotone in cl and therefore send a free search to the upper bound.
    # Only informative because om_g is now stochastic.
    ["std(pi_g - pi_s)", "corr(pi_g - pi_s, om_g)"],
    # 64-77 (2026-08-21): PERSISTENCE. Until today this 63-moment vector held
    # exactly ONE autocorrelation, autocorr(Q), against three free persistence
    # parameters (rho_A, rho_om, rho_zeta). They were identified only through
    # the way the HP filter reweights variance across frequencies — which is why
    # rho_A ran to its 0.99 bound: nothing in the objective pushed back on
    # maximum persistence. Appended at the END so every existing index and every
    # hardcoded block slice is unchanged.
    ["autocorr(GDP)", "autocorr(pi)"],
    ["autocorr(Y_$(i))" for i in 1:12],
    # 78-84 (2026-08-21): the literature-standard block. Appended, again, so no
    # existing index moves. See build_weighting_matrix for what was switched OFF
    # to make room — this is a REPLACEMENT of unprecedented moments by standard
    # ones, not an addition on top.
    ["rbar: avg pairwise corr(Y_i,Y_j)"],
    ["std(L) goods (wtd avg)", "std(L) services (wtd avg)"],
    ["std(C)/std(GDP)", "std(I)/std(GDP)", "corr(C,GDP)", "corr(I,GDP)"])

const MOMENT_BLOCKS = [
    (1:12,  "std(Y_i) sectoral output vol"),
    (13:24, "std(PH_i) sectoral price vol"),
    (25:36, "std(L_i) sectoral labor vol"),
    (37:43, "aggregates (GDP, pi, TB, Q)"),
    (44:46, "rank correlations"),
    (47:58, "corr(Y_i,PH_i) supply/demand mix"),
    (59:60, "labor comovement corr(N,·)"),
    (61:61, "goods expenditure share"),
    (62:63, "goods-services relative price (identifies cl)"),
    (64:65, "aggregate persistence autocorr(GDP,pi)"),
    (66:77, "sectoral persistence autocorr(Y_i)"),
    (78:78, "cross-sectoral comovement (rbar)"),
    (79:80, "sectoral labour dispersion G/S"),
    (81:84, "SOE great ratios (C, I)"),
]

# ---- Weighting matrix ------------------------------------------------------ #
# Sectoral value-added shares, % of total VA. Fixed, for ECONOMIC-SIZE moment
# weighting. Order = the 12 model sectors.
#
# SOURCE (2026-08-19): Chilean IO tables 2021, Data/2021_Cuadros_12x12.xlsx,
# Cuadro 23 "Valor agregado" — the same table the calibration is built from.
#
# WAS: [5.07, 12.63, 15.87, 2.90, 3.14, 3.34, 10.93, 6.71, 2.13, 26.03, 11.08,
# 0.17] — hardcoded from an OLD MODEL RUN, not from data, and that run used the
# pre-2026-08-19 cost-base alpha convention, so it was stale twice over. It
# systematically downweighted exactly the sectors the model fits worst:
#
#   sector                  old      data     ratio
#   Administracion publica  0.17%    5.08%    x29.9
#   Serv. inmobiliarios     2.13%    8.55%    x4.0
#   Comercio                3.34%   12.66%    x3.8
#   Construccion            3.14%    6.45%    x2.1
#   Serv. empresariales    26.03%    9.75%    x0.37
#
# Effect on the criterion is small (total objective 15.09 -> 15.13 at the July
# theta) because the sectoral blocks are only ~21% of it — but it changes WHICH
# sectors the optimiser chases, and a model-derived weight matrix is not
# defensible in a replication package.
const SECTOR_VA_SHARE = let s = [3.92, 15.78, 9.54, 2.79, 6.45, 12.66,
                                 8.31,  3.91, 8.55, 9.75, 13.27, 5.08]
    s ./ sum(s)
end

"""
Sectors whose national-accounts output is NOT a market outcome, and whose
volatility and price-quantity correlation are therefore accounting conventions:

  9  Real Estate          — dominated by imputed rent on owner-occupied housing
  12 Public Administration — output measured by inputs (compensation of employees)

See the NON-MARKET SECTORS block at the end of `build_weighting_matrix` for what
this does and why. Referenced by the paper's data section.
"""
const NONMARKET_SECTORS = [9, 12]

function build_weighting_matrix(dm::Vector{<:Real})
    w = ones(N_MOMENTS)
    # Sectoral volatility moments 1:36 = output(1:12), price(13:24), labor(25:36).
    # Weight each by the sector's VALUE-ADDED SHARE (economic size), NOT 1/d².
    # WHY: 1/d^2 pathologically over-weighted the SMALLEST-volatility sector —
    # Public Admin (data std 0.011) received weight ~7650, about 1200x
    # Agriculture, and its std(Y) miss alone was 40% of the objective.
    # (The original note here justified this with "0.17% of VA", which was the
    # MODEL's public-admin share under the old calibration, not the data's —
    # Cuadro 23 puts it at 5.08%. The 1/d^2 argument stands on its own.)
    # Size-weighting makes the objective track economic relevance; cross-sector
    # ORDERING stays disciplined by the rank-correlation moments (44-46).
    # SECT_BLOCK_W = total weight per 12-sector block (tunable).
    SECT_BLOCK_W = 1000.0
    for k in 1:36
        sec = ((k - 1) % 12) + 1
        w[k] = SECT_BLOCK_W * SECTOR_VA_SHARE[sec]
    end
    # 25-36, the twelve std(L_i) — UNTARGETED as of 2026-08-21, replaced by the
    # two goods/services aggregates at 79-80.
    #
    # FGI (2023) is the only paper in this literature that targets sectoral
    # employment at all, and they target TWO cross-sectional dispersion
    # statistics — one for goods, one for services — not twelve individual
    # sector volatilities. Twelve separate targets put a great deal of weight on
    # the least reliable series in the set: AFC/Seguro de Cesantia coverage
    # phases in through the early sample at very different rates by sector, and
    # the Ley de Proteccion al Empleo distorts 2020-21 (already excluded).
    # Aggregating to goods and services averages most of that away.
    #
    # Still computed and printed sector by sector, as untargeted diagnostics.
    let wl = parse(Float64, get(ENV, "SMM_W_STDL_SECTORAL", "0.0"))
        for k in 25:36
            w[k] = wl * SECT_BLOCK_W * SECTOR_VA_SHARE[((k - 1) % 12) + 1]
        end
    end
    # Aggregate stds (GDP, pi, TB, Q): keep inverse-squared-data weighting.
    for k in [37, 38, 40, 41]
        d = abs(dm[k]); w[k] = d > 1e-4 ? 1.0/d^2 : 1.0/0.01^2
    end
    # 39 = corr(GDP,pi). The old note here read "structurally hard for supply-
    # shock model" and cut the weight to 0.20. That has the economics backwards.
    # A supply shock raises output and lowers prices, so a SUPPLY-driven economy
    # is exactly what produces corr(GDP,pi) < 0; it is a DEMAND-driven model
    # that struggles with the data's negative sign. The model's problem was
    # never the sign — it delivered -0.162 against -0.421 — it was that the
    # correlation was too WEAK, which is the same message as lambda_om = 3.14:
    # too much demand in the shock mix.
    #
    # Most of the residual gap was the pandemic. On the data, HP-filtered:
    #     corr(GDP,pi)  full sample      -0.392
    #                   excl. 2020Q1-21Q2 -0.213
    # against a model -0.162. With COVID excluded (compute_data_moments.jl)
    # this moment is very nearly matched already.
    #
    # So it is restored to full weight, and treated as what it is: the AGGREGATE
    # counterpart of the corr(Y_i,PH_i) block, carrying information about the
    # same supply/demand mix. Weight 3.0 to match that block — bounded in
    # [-1,1], so a fixed weight, per the convention above.
    w[39] = parse(Float64, get(ENV, "SMM_W_CORR_GDPPI", "3.0"))
    # 42 = autocorr(Q). The old note said this identifies rho_pvstar, but
    # rho_pvstar has been PINNED at its measured ToT AR(1) since the shock
    # redesign, so this moment was identifying nothing. It is now the main
    # source of information on rho_zeta — see the note at sigma_zeta's bound in
    # the LB/UB block — and the model misses it badly (0.426 vs 0.716).
    w[42]  = 2.0
    # 44-46 RANK CORRELATIONS — UNTARGETED as of 2026-08-21, still computed and
    # printed. This is a considered removal, not "the model could not match them".
    #
    # A literature pass over Ferrante-Graves-Iacoviello (2023), Atalay (2017),
    # Foerster-Sarte-Watson (2011), Rubbo (2023), Luttini-Pasten-Rubbo (2024),
    # Baqaee-Farhi (2022), Imbs-Jondeau-Pelgrin (2011), Garcia-Cicco-Pancrazi-
    # Uribe (2010), Schmitt-Grohe-Uribe (2018) and XMAS found the words
    # "Spearman", "rank correlation" and "Kendall" ZERO times. Nobody targets a
    # rank statistic of a second moment. The closest relative is FGI's
    # rho(y_data, y_model), which is PEARSON on the level of sectoral changes —
    # "is the right sector in the right place" — not Spearman on the ORDERING of
    # volatilities.
    #
    # They are also badly behaved as an objective: a Spearman correlation is a
    # step function of theta, so it is locally flat and globally cliffed. That is
    # visible in the CMA-ES traces, which sit on identical objective values for
    # hundreds of evaluations.
    #
    # They are replaced by moment 78, rbar, which measures the same economics
    # (cross-sectoral comovement) with the statistic this literature actually
    # uses, and is smooth in theta.
    #
    # Reporting them as untargeted also fills a real gap: FGI, Baqaee-Farhi,
    # GCPU, SGU and Rubbo all reserve something for out-of-sample validation and
    # this objective reserved nothing. SMM_W_RANK restores a positive weight.
    let wrank = parse(Float64, get(ENV, "SMM_W_RANK", "0.0"))
        w[44] = wrank; w[45] = wrank; w[46] = wrank
    end
    # 46 = LABOUR rank correlation. KEPT TARGETED at the same weight (2026-08-21).
    #
    # This moment was briefly set to zero earlier the same day on the grounds
    # that it was unattainable — spearman(std L_i, std Y_i) = -0.231 in the data
    # against +0.336 in the model, a sign the model cannot flip. That argument
    # was WRONG, and the record is worth keeping because the failure mode is
    # easy to repeat: the -0.231 was not a fact about Chile, it was a SAMPLE
    # MISMATCH. std_L and std_PH were being computed on 2006Q1-2023Q4 while
    # std_Y and corr_YPH used 2013Q1-2023Q4 (the SA output vintage starts in
    # 2013). Two cross-sections measured over different decades. Align them and
    #     spearman(std L_i, std Y_i) = +0.000
    # The -0.231 came almost entirely from AFC coverage phase-in over 2006-2012
    # in Mining, Finance and Public Admin. Fixed in compute_data_moments.jl §4b.
    #
    # +0.000 versus a model +0.336 is a real gap but an ordinary one: no sign
    # impossibility, so it stays in the objective and the model has to answer
    # for it. Note the data source is sound — AFC / Seguro de Cesantía
    # administrative records, which is the intended source; a Poisson/binomial
    # cell-size noise floor is only ~15% of the measured std and correlates just
    # +0.14 with std(L_i), so the cross-section is not driven by sampling noise.
    #
    # OPEN ISSUE for the 2020-21 window, worth a robustness check rather than a
    # weight change: under the Ley de Protección al Empleo (21.227, April 2020)
    # suspended workers stayed on the AFC register, so AFC headcount barely fell
    # in exactly the sectors whose output collapsed (Personal services -20.6%
    # output vs -4.5% employment; Trade/Hotels -24.6% vs -10.5%). Excluding
    # 2020Q1-2021Q2 moves the aligned rank correlation from +0.000 to -0.182.
    #
    # SMM_W_LABOR_RANK still overrides moment 46 alone, on top of SMM_W_RANK.
    haskey(ENV, "SMM_W_LABOR_RANK") && (w[46] = parse(Float64, ENV["SMM_W_LABOR_RANK"]))
    # corr(Y_i,PH_i): FIXED weight (2026-07-09). Old proportional 1.5/d²
    # exploded for near-zero data correlations (sector 10: w≈30,800) and made
    # this block 99.5% of the objective. Correlations are bounded [-1,1] →
    # fixed weight, 1.5× the rank weight to keep identification emphasis.
    for k in 47:58
        w[k] = 3.0
    end
    w[59] = 2.0; w[60] = 2.0   # corr(N,GDP), corr(N,GDP/N)
    # std(omG), the goods expenditure share (2026-08-19). Inverse-squared-data
    # weighting, as for the other aggregate std moments (37,38,40,41). This is
    # the moment that identifies sigma_omg — under Cobb-Douglas omega_t IS the
    # goods expenditure share (FGI 2023 eq. 12), so the mapping is direct.
    let d = abs(dm[61]); w[61] = d > 1e-4 ? 1.0/d^2 : 1.0/0.01^2 end
    # 62 std(pi_g - pi_s): inverse-squared-data, consistent with the other
    # aggregate std moments (37,38,40,41). 63 corr(pi_g - pi_s, om_g): fixed
    # weight, as for every other correlation — bounded in [-1,1], so a
    # proportional weight would explode near zero (that pathology is what the
    # corr(Y_i,PH_i) note above records). 3.0 matches the corr(Y_i,PH_i) block,
    # i.e. the same emphasis as the other identification-carrying correlations.
    let d = abs(dm[62]); w[62] = d > 1e-4 ? 1.0/d^2 : 1.0/0.01^2 end
    w[63] = 3.0
    # 64-77 PERSISTENCE (2026-08-21). Autocorrelations are bounded in [-1,1],
    # so fixed weights, per the convention above — a proportional weight would
    # explode for a sector whose data autocorrelation is near zero.
    #
    # 64-65 aggregate: 2.0, matching autocorr(Q) (w[42]). These are what
    # discipline rho_A and stop it running to its bound.
    # 66-77 sectoral: 1.0 each. Deliberately modest. Twelve new moments at
    # correlation-scale weights would swamp a total objective of order 10; at
    # 1.0 with typical misses of 0.2-0.4 the block carries ~1, comparable to
    # the std(PH_i) block. The point of these twelve is to make the COMMON
    # rho_A restriction testable, not to dominate the fit.
    w[64] = parse(Float64, get(ENV, "SMM_W_AC_AGG",  "2.0"))
    w[65] = w[64]
    let wac = parse(Float64, get(ENV, "SMM_W_AC_SEC", "1.0"))
        for k in 66:77
            w[k] = wac
        end
    end
    # ---- 78-84: the literature-standard replacements (2026-08-21) --------- #
    # 78 rbar — a correlation, bounded, so a fixed weight, at the same 3.0 as the
    #    other identification-carrying correlations. It replaces THREE rank
    #    moments that between them carried 6.0, so the block weight falls.
    w[78] = parse(Float64, get(ENV, "SMM_W_RBAR", "3.0"))
    # 79-80 goods/services average sectoral employment volatility. Inverse-
    #    squared-data, as for every other std moment. Between them these replace
    #    the twelve std(L_i).
    for k in 79:80
        d = abs(dm[k]); w[k] = d > 1e-4 ? 1.0/d^2 : 1.0/0.01^2
    end
    # 81-84 the SOE great ratios. std(C)/std(GDP) and std(I)/std(GDP) are RATIOS
    #    of order 1, so inverse-squared-data gives them a sensible scale;
    #    corr(C,GDP) and corr(I,GDP) are correlations, so fixed weight.
    #    GCPU (2010) Table 4 and XMAS Table 5 both report exactly this block.
    for k in 81:82
        d = abs(dm[k]); w[k] = d > 1e-3 ? 1.0/d^2 : 1.0
    end
    w[83] = 3.0; w[84] = 3.0

    # ---- NON-MARKET SECTORS (2026-08-24) ----------------------------------- #
    #
    # Real Estate (9) and Public Administration (12) are not market outcomes in
    # the national accounts, so their output, deflator, and the correlation
    # between them are accounting conventions rather than economic behaviour:
    #
    #   * Real Estate output is dominated by IMPUTED RENT on owner-occupied
    #     housing. It is constructed from the housing stock and a rental
    #     imputation, not from transactions, so it barely moves at business-cycle
    #     frequency and it has no market price to correlate with quantity.
    #   * Public Administration output is measured by INPUTS (compensation of
    #     employees), the standard convention for non-market government services.
    #     Its "price" is a deflator built from wages, so corr(Y,PH) is a
    #     restatement of the wage-employment split, not a supply/demand mix.
    #
    # The data say exactly this. These two are the LEAST volatile sectors in the
    # panel by a wide margin — std(Y) = 0.0081 and 0.0082 against 0.017-0.054 for
    # the other ten. That is a measurement artefact of smoothing-by-construction.
    #
    # It was not harmless. At the warm-start optimum of 2026-08-24, corr(Y_9,PH_9)
    # ALONE was 16.7% of the objective (data -0.400, model +0.289 — the model
    # cannot even get the sign, and should not be asked to), and the block
    # corr(Y_i,PH_i) was 51% of the total. The estimator was spending half its
    # effort on twelve moments of which the single largest is an imputation.
    #
    # This is why the literature works with market output: Foerster, Sarte &
    # Watson (2011 JPE) use industrial production and Atalay (2017) manufacturing.
    #
    # Weight 0.0 = computed and PRINTED as an untargeted diagnostic, never scored
    # — the same treatment already given to the twelve std(L_i) at 25-36. Set
    # SMM_W_NONMARKET to a fraction (e.g. 0.25) to downweight instead of drop.
    #
    # NOT changed here, and worth deciding separately: rbar (78) is still the
    # average over all 66 sector pairs, including the 21 pairs involving 9 or 12.
    # Consistency argues for recomputing it over the ten market sectors, but that
    # changes the DATA target too, so it needs a compute_data_moments.jl re-run.
    #
    # JUDGEMENT CALL LEFT OPEN: Personal Services (11) is the second-largest
    # contributor (10.5%) and in the Chilean CCNN it bundles education and health,
    # much of which is public and also input-measured. It is a MIXED sector, so it
    # is left targeted here. If it is added later, say so in the paper.
    let wnm = parse(Float64, get(ENV, "SMM_W_NONMARKET", "0.0"))
        for s in NONMARKET_SECTORS
            w[s]      *= wnm      # std(Y_i)
            w[12 + s] *= wnm      # std(PH_i)
            w[46 + s] *= wnm      # corr(Y_i,PH_i)
        end
    end

    return Diagonal(w) |> Matrix
end

# ---- Report printers ------------------------------------------------------- #
function print_param_table(θ::AbstractVector; io=stdout)
    @printf(io, "\n  %-3s %-16s %12s %10s %10s  %s\n",
            "#", "Parameter", "Value", "LB", "UB", "Bound?")
    println(io, "  ", repeat("-", 66))
    for k in 1:N_THETA
        span_k = UB[k] - LB[k]
        flag = θ[k] <= LB[k] + 0.02*span_k ? "<< at LB" :
               θ[k] >= UB[k] - 0.02*span_k ? ">> at UB" : ""
        @printf(io, "  %-3d %-16s %12.4f %10.3f %10.3f  %s\n",
                k, PARAM_LABELS[k], θ[k], LB[k], UB[k], flag)
    end
    println(io, "  ", repeat("-", 66))
    println(io, "  'at LB/UB' = within 2% of a bound: not identified there, or bound binds.")
end

function print_fit_table(dm::AbstractVector, mm::AbstractVector, W::AbstractMatrix; io=stdout)
    ψ  = dm .- mm
    wd = [W[i,i]*ψ[i]^2 for i in 1:N_MOMENTS]
    tot = sum(wd)
    @printf(io, "\n  %-34s %9s %9s %9s %10s %6s\n",
            "Moment", "Data", "Model", "Diff", "W*Diff2", "%obj")
    println(io, "  ", repeat("-", 84))
    for (rng, lbl) in MOMENT_BLOCKS
        bsum = sum(wd[rng])
        @printf(io, "  -- %-48s block %8.3f  %5.1f%% --\n", lbl, bsum, 100bsum/tot)
        for i in rng
            @printf(io, "  %-34s %9.5f %9.5f %+9.5f %10.4f %5.1f%%\n",
                    MOMENT_NAMES[i], dm[i], mm[i], ψ[i], wd[i], 100wd[i]/tot)
        end
    end
    println(io, "  ", repeat("-", 84))
    @printf(io, "  %-34s %29s %10.4f %6s\n", "TOTAL OBJECTIVE", "", tot, "100%")
end

# =========================================================================== #
#  OBJECTIVE PROVENANCE  (added 2026-08-19)                                   #
# =========================================================================== #
# WHY. The checkpoint written 2026-07-24 10:21 carries obj = 21.4718.
# Re-evaluating the SAME θ on 2026-08-19 gives 15.0909, with every block of the
# decomposition moved (Rank 8.639→4.777, PH 4.180→1.742, Agg 1.313→0.837).
# That is NOT the estimator disagreeing with main_SOE_gap.jl. Between 10:21 and
# 13:40 that same day the model changed underneath the checkpoint:
#
#   10:48  NK_SOE_lev_gap2.mod  + eps_pc   (world copper price — a 28th ACTIVE
#                                           shock the 10:21 run never had)
#   11:16  NK_SOE_lev_gap2.mod  + choice3
#   13:23  NK_SOE_lev_gap2.mod  + ownership
#   13:40  NK_SOE_lev_gap2.mod  + GDP_vol  (volume GDP — redefines std(GDP),
#                                           corr(GDP,pi), corr(GDP,Q),
#                                           corr(N,GDP), corr(N,GDP/N))
#
# The stored objective was simply computed on a model that no longer exists.
# A stored objective is comparable to a fresh one only when EVERY file that
# defines the objective is byte-identical. Stamp it on write, verify it on read.
#
# Deliberately dependency-free (no SHA / no new `using`): the stamp is
# "basename:bytes:mtime" per file. Byte count catches ordinary edits; mtime
# catches same-size edits.

const OBJ_PROVENANCE_FILE = "objective_provenance.txt"

"""
    objective_dep_files(script_dir, mod_dir, data_dir) -> Vector{String}

Every file whose contents change the VALUE of the SMM objective: the model, the
moment/weight definitions, the two solver front-ends, and the data moments.
Missing files are dropped silently so this works on a partial checkout.
"""
function objective_dep_files(script_dir::AbstractString,
                             mod_dir::AbstractString,
                             data_dir::AbstractString)
    return filter(isfile, [
        # model + moment/weight definitions + steady state
        joinpath(mod_dir,    "NK_SOE_lev_gap2.mod"),
        joinpath(script_dir, "utils.jl"),
        joinpath(script_dir, "smm_estimation.jl"),
        joinpath(script_dir, "smm_model_moments.jl"),
        joinpath(script_dir, "steady_ntwsoe_system.jl"),
        joinpath(script_dir, "steady_ntwsoe.jl"),
        # data moments (the LHS of the objective)
        joinpath(data_dir,   "sectoral_moments.csv"),
        joinpath(data_dir,   "aggregate_moments.csv"),
        # calibration inputs — these move the steady state, hence every model
        # moment. sector_calibration.csv in particular: its alpha/alpha_V
        # convention changed on 2026-08-19 (cost base -> gross output, to match
        # Ferrante, Graves & Iacoviello 2023), which shifts the whole SS.
        joinpath(data_dir,   "sector_calibration.csv"),
        joinpath(data_dir,   "IO_2021_chile_domestic.csv"),
        joinpath(data_dir,   "IO_2021_chile.csv"),
        joinpath(data_dir,   "fpa_vector_few_industries_chile.csv"),
        joinpath(data_dir,   "sectoral_shock_calibration.csv"),
        joinpath(data_dir,   "external_shock_calibration.csv"),
    ])
end

"""
    objective_fingerprint(files) -> String

One `basename:bytes:mtime` line per file, newline separated.
"""
objective_fingerprint(files::AbstractVector{<:AbstractString}) =
    join([@sprintf("%s:%d:%.0f", basename(f), filesize(f), mtime(f)) for f in files], "\n")

"""
    write_objective_provenance(dir, files)

Record the current fingerprint next to the estimation output. Call this from
`save_checkpoint` so every stored objective carries the model it was computed on.
"""
function write_objective_provenance(dir::AbstractString,
                                    files::AbstractVector{<:AbstractString})
    open(joinpath(dir, OBJ_PROVENANCE_FILE), "w") do io
        println(io, "# Fingerprint of every file that defines the SMM objective.")
        println(io, "# A stored obj_hat is comparable to a fresh evaluation ONLY if")
        println(io, "# this block still matches. See utils.jl OBJECTIVE PROVENANCE.")
        println(io, "# written ", Libc.strftime("%Y-%m-%d %H:%M:%S", time()))
        println(io, objective_fingerprint(files))
    end
    return nothing
end

"""
    check_objective_provenance(dir, files, θ_mtime) -> (comparable::Bool, changed::Vector{String})

`comparable == false` means a stored objective from `dir` must NOT be compared
against, or reported alongside, a freshly computed one. `changed` names the
offending files.

Falls back to an mtime comparison when no provenance file is present (every
checkpoint written before 2026-08-19). The fallback is conservative: it flags
anything modified after the θ file, which is the correct default.
"""
function check_objective_provenance(dir::AbstractString,
                                    files::AbstractVector{<:AbstractString},
                                    θ_mtime::Real)
    prov = joinpath(dir, OBJ_PROVENANCE_FILE)
    if isfile(prov)
        stored = [l for l in split(read(prov, String), '\n')
                  if !isempty(l) && !startswith(l, "#")]
        stored_d = Dict(String(first(split(l, ':'))) => String(l) for l in stored)
        changed = String[]
        for l in split(objective_fingerprint(files), '\n')
            nm = String(first(split(l, ':')))
            get(stored_d, nm, "") == String(l) || push!(changed, nm)
        end
        return isempty(changed), changed
    end
    # No stamp: fall back to mtime. 1 s slack absorbs timestamp granularity.
    newer = [basename(f) for f in files if mtime(f) > θ_mtime + 1.0]
    return isempty(newer), newer
end

end  # include guard (_SMM_SHARED_DEFS_LOADED)
