# NB: this file was automatically generated by Dynare
#     from NK_SOE_lev_gap2.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(491, 571);
gp = zeros(491, 642, 571);
end
return (rp, gp)
end
