# NB: this file was automatically generated by Dynare
#     from NK_SOE_lev_gap2.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(491, 573);
gp = zeros(491, 491, 573);
end
return (rp, gp)
end
