# NB: this file was automatically generated by Dynare
#     from NK_SOE_lev_gap2.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(570, 607);
gp = zeros(570, 726, 607);
end
return (rp, gp)
end
